## **LLM Benchmarking**

### **Data Preparation**

Pull test data and class names from artifacts

In [1]:
import joblib

x_test = joblib.load(r".\Artifacts\x_test.pkl")
y_test = joblib.load(r".\Artifacts\y_test.pkl")
class_names = joblib.load(r".\Artifacts\class_names.pkl")

print("Data split loaded")

Data split loaded

In [27]:
x_test[:10]

['today tomorrow try move mountains cross fingers',
 'typa girl bullied lesbians high school',
 'cool woman gave directions polling place whose wee boy always runs around high heels ‘girls’ clothes he’s told gets bullied ‘poof’',
 'need teach version quran terrorists killing people world blast selves kill innocent isis terror org bearing enough bull shits cant buy version see jehad gazwa hind darulharb',
 'rome destroy coliseum roman forum every building statue romans slaves persecutedkilled christians support radical “muslims” iraq syria blew historic cultural sites',
 'try hide jihadi propaganda know hell gys specly jihadin aunty urgnt need hide islamic terrorisms behind typ artificial propaganda coz current scenario exposed infrnt whole world',
 'city college',
 'pepperidge farm remembers',
 'added feminazi white knight professional victims terminology',
 'blm something know muslim leaders record stating use manipulate goals quoted saying islam’s ‘useful idiots’ islam says that white america']

In [24]:
y_test[:10]

array([4, 0, 0, 5, 5, 5, 3, 4, 4, 5])

In [28]:
len(x_test), len(y_test)

(11923, 11923)

In [4]:
class_names

Index(['age', 'ethnicity', 'gender', 'not_cyberbullying',
       'other_cyberbullying', 'religion'],
      dtype='object')

### **LLM: Qwen2.5:7b-Instruct**

#### **Predictions**

In [15]:
import os
import json
import re
import time
from pathlib import Path
import requests
import numpy as np
import pandas as pd
import joblib

# ----------------------------
# Ollama configuration
# ----------------------------
OLLAMA_BASE_URL = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "qwen2.5:7b-instruct")  # e.g., deepseek-r1:7b, qwen2.5:7b-instruct
MAX_OLLAMA_CASES = None  # set integer (e.g., 200) for a smaller quick run
REQUEST_TIMEOUT_SECONDS = 120
MAX_RETRIES = 3

# Checkpoint/resume configuration
CHECKPOINT_EVERY = 25
RESUME_FROM_CHECKPOINT = True
RESET_CHECKPOINT = False

# If earlier cells were not run, load artifacts here as a fallback.
if "x_test" not in globals():
    x_test = joblib.load(r".\Artifacts\x_test.pkl")
if "y_test" not in globals():
    y_test = joblib.load(r".\Artifacts\y_test.pkl")
if "class_names" not in globals():
    class_names = joblib.load(r".\Artifacts\class_names.pkl")

class_names_list = list(class_names)
label_to_id = {label: i for i, label in enumerate(class_names_list)}
FALLBACK_LABEL = "other_cyberbullying"

if MAX_OLLAMA_CASES is None:
    x_eval = list(x_test)
    y_eval = np.asarray(y_test)
else:
    x_eval = list(x_test)[:MAX_OLLAMA_CASES]
    y_eval = np.asarray(y_test)[:MAX_OLLAMA_CASES]

artifacts_dir = Path(r".\Artifacts")
artifacts_dir.mkdir(parents=True, exist_ok=True)
safe_model_name = re.sub(r"[^a-zA-Z0-9_.-]", "_", OLLAMA_MODEL)
checkpoint_path = artifacts_dir / f"ollama_checkpoint_{safe_model_name}.pkl"
predictions_path = artifacts_dir / f"ollama_predictions_{safe_model_name}.pkl"

if RESET_CHECKPOINT and checkpoint_path.exists():
    checkpoint_path.unlink()
    print(f"Deleted old checkpoint: {checkpoint_path}")

SYSTEM_PROMPT = f"""You are an expert annotator for cyberbullying tweet classification.

Valid labels: {class_names_list}

Rules:
1) Return exactly one label from the valid label list.
2) Output STRICT JSON only, with this schema:
   {{"label": "<one_valid_label>"}}
3) Do not output markdown, code fences, or any extra keys.
"""

def _parse_json_payload(raw_text: str):
    text = (raw_text or "").strip()
    try:
        return json.loads(text)
    except Exception:
        pass
    text = re.sub(r"^```(?:json)?\s*|\s*```$", "", text, flags=re.IGNORECASE | re.DOTALL).strip()
    return json.loads(text)

def _normalize_text(s: str) -> str:
    return re.sub(r"[^a-z0-9_]+", "", (s or "").strip().lower())

normalized_label_to_canonical = {
    _normalize_text(label): label for label in class_names_list
}

def _map_to_valid_label(raw_label: str) -> str:
    # 1) Exact canonical label
    if raw_label in label_to_id:
        return raw_label

    raw_norm = _normalize_text(raw_label)

    # 2) Exact normalized match (handles spaces/case/punctuation variants)
    if raw_norm in normalized_label_to_canonical:
        return normalized_label_to_canonical[raw_norm]

    # 3) Substring match against any class label
    for cls in class_names_list:
        cls_norm = _normalize_text(cls)
        if cls_norm and cls_norm in raw_norm:
            return cls

    # 4) Fallback if no class detected
    if FALLBACK_LABEL in label_to_id:
        return FALLBACK_LABEL

    raise ValueError(
        f"Invalid label returned and fallback label not found: {raw_label}. "
        f"Expected one of {class_names_list} with fallback '{FALLBACK_LABEL}'."
    )

def ollama_predict_one(tweet_text: str):
    last_error = None
    payload = {
        "model": OLLAMA_MODEL,
        "stream": False,
        "format": "json",
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": f"Classify this tweet:\n\n{tweet_text}"},
        ],
        "options": {"temperature": 0},
    }

    for attempt in range(1, MAX_RETRIES + 1):
        try:
            resp = requests.post(
                f"{OLLAMA_BASE_URL}/api/chat",
                json=payload,
                timeout=REQUEST_TIMEOUT_SECONDS,
            )
            resp.raise_for_status()
            data = resp.json()
            content = data.get("message", {}).get("content", "")
            out = _parse_json_payload(content)
            raw_label = str(out.get("label", "")).strip()
            final_label = _map_to_valid_label(raw_label)
            return label_to_id[final_label], final_label
        except Exception as err:
            last_error = err
            if attempt < MAX_RETRIES:
                time.sleep(1.2 * attempt)

    raise RuntimeError(f"Ollama prediction failed after retries: {last_error}")

def save_checkpoint(next_index: int, pred_ids, pred_rows):
    state = {
        "model": OLLAMA_MODEL,
        "x_eval_size": len(x_eval),
        "next_index": int(next_index),
        "pred_ids": list(pred_ids),
        "pred_rows": list(pred_rows),
        "saved_at_unix": time.time(),
    }
    joblib.dump(state, checkpoint_path)

# ----------------------------
# Resume from checkpoint if available
# ----------------------------
ollama_pred_ids = []
ollama_rows = []
start_index = 0

if RESUME_FROM_CHECKPOINT and checkpoint_path.exists():
    state = joblib.load(checkpoint_path)
    same_model = state.get("model") == OLLAMA_MODEL
    same_size = int(state.get("x_eval_size", -1)) == len(x_eval)
    if same_model and same_size:
        ollama_pred_ids = list(state.get("pred_ids", []))
        ollama_rows = list(state.get("pred_rows", []))
        start_index = int(state.get("next_index", len(ollama_pred_ids)))
        start_index = max(0, min(start_index, len(x_eval)))
        print(f"Resumed from checkpoint: {checkpoint_path}")
        print(f"Loaded {len(ollama_pred_ids)} saved predictions; continuing from index {start_index}")
    else:
        print("Checkpoint found but skipped due to model/test-size mismatch.")
        print(f"Checkpoint path: {checkpoint_path}")

# ----------------------------
# Run Ollama prediction for each tweet
# ----------------------------
total = len(x_eval)
start_time = time.time()

for idx in range(start_index, total):
    tweet_text = x_eval[idx]
    pred_id, pred_label = ollama_predict_one(str(tweet_text))
    ollama_pred_ids.append(int(pred_id))
    ollama_rows.append({
        "tweet": str(tweet_text),
        "y_test_label": class_names_list[int(y_eval[idx])],
        "ollama_prediction": pred_label,
    })

    processed = idx + 1
    if (processed % CHECKPOINT_EVERY == 0) or (processed == total):
        save_checkpoint(next_index=processed, pred_ids=ollama_pred_ids, pred_rows=ollama_rows)
        elapsed = time.time() - start_time
        done_now = max(1, processed - start_index)
        sec_per_tweet = elapsed / done_now
        remaining = total - processed
        eta_min = (remaining * sec_per_tweet) / 60.0
        print(f"Ollama progress: {processed}/{total} | checkpoint saved | ETA ~ {eta_min:.1f} min")

# Convert and save final artifacts
ollama_pred_ids = np.asarray(ollama_pred_ids, dtype=int)
ollama_pred_df = pd.DataFrame(ollama_rows)
ollama_pred_df["is_match"] = ollama_pred_df["y_test_label"] == ollama_pred_df["ollama_prediction"]

prediction_compare_df = ollama_pred_df[[
    "tweet",
    "y_test_label",
    "ollama_prediction",
    "is_match",
]].copy()

joblib.dump(
    {
        "ollama_pred_ids": ollama_pred_ids,
        "prediction_compare_df": prediction_compare_df,
        "model": OLLAMA_MODEL,
        "x_eval_size": len(x_eval),
    },
    predictions_path,
 )

display(prediction_compare_df.head(20))
print(f"Done. Collected {len(ollama_pred_ids)} predictions from model: {OLLAMA_MODEL}")
print(f"Total exact label matches: {int(prediction_compare_df['is_match'].sum())}/{len(prediction_compare_df)}")
print(f"Checkpoint file: {checkpoint_path}")
print(f"Predictions artifact: {predictions_path}")

Ollama progress: 25/11923 | checkpoint saved | ETA ~ 1063.2 min
Ollama progress: 50/11923 | checkpoint saved | ETA ~ 1083.9 min
Ollama progress: 75/11923 | checkpoint saved | ETA ~ 1075.7 min
Ollama progress: 100/11923 | checkpoint saved | ETA ~ 1102.7 min
Ollama progress: 125/11923 | checkpoint saved | ETA ~ 1120.7 min
Ollama progress: 150/11923 | checkpoint saved | ETA ~ 1130.2 min
Ollama progress: 175/11923 | checkpoint saved | ETA ~ 1142.3 min
Ollama progress: 200/11923 | checkpoint saved | ETA ~ 1140.6 min
Ollama progress: 225/11923 | checkpoint saved | ETA ~ 1143.3 min
Ollama progress: 250/11923 | checkpoint saved | ETA ~ 1150.0 min
Ollama progress: 275/11923 | checkpoint saved | ETA ~ 1156.7 min
Ollama progress: 300/11923 | checkpoint saved | ETA ~ 1155.2 min
Ollama progress: 325/11923 | checkpoint saved | ETA ~ 1146.6 min
Ollama progress: 350/11923 | checkpoint saved | ETA ~ 1140.9 min
Ollama progress: 375/11923 | checkpoint saved | ETA ~ 1133.7 min
Ollama progress: 400/11923 | checkpoint saved | ETA ~ 1128.1 min
Ollama progress: 425/11923 | checkpoint saved | ETA ~ 1118.8 min
Ollama progress: 450/11923 | checkpoint saved | ETA ~ 1110.6 min
Ollama progress: 475/11923 | checkpoint saved | ETA ~ 1103.8 min
Ollama progress: 500/11923 | checkpoint saved | ETA ~ 1098.6 min
Ollama progress: 525/11923 | checkpoint saved | ETA ~ 1095.3 min
Ollama progress: 550/11923 | checkpoint saved | ETA ~ 1088.8 min
Ollama progress: 575/11923 | checkpoint saved | ETA ~ 1083.5 min
Ollama progress: 600/11923 | checkpoint saved | ETA ~ 1079.0 min
Ollama progress: 625/11923 | checkpoint saved | ETA ~ 1075.1 min
Ollama progress: 650/11923 | checkpoint saved | ETA ~ 1071.6 min
Ollama progress: 675/11923 | checkpoint saved | ETA ~ 1069.5 min
Ollama progress: 700/11923 | checkpoint saved | ETA ~ 1065.8 min
Ollama progress: 725/11923 | checkpoint saved | ETA ~ 1064.1 min
Ollama progress: 750/11923 | checkpoint saved | ETA ~ 1061.1 min
Ollama progress: 775/11923 | checkpoint saved | ETA ~ 1056.7 min
Ollama progress: 800/11923 | checkpoint saved | ETA ~ 1054.0 min
Ollama progress: 825/11923 | checkpoint saved | ETA ~ 1051.9 min
Ollama progress: 850/11923 | checkpoint saved | ETA ~ 1049.0 min
Ollama progress: 875/11923 | checkpoint saved | ETA ~ 1045.9 min
Ollama progress: 900/11923 | checkpoint saved | ETA ~ 1042.3 min
Ollama progress: 925/11923 | checkpoint saved | ETA ~ 1040.1 min
Ollama progress: 950/11923 | checkpoint saved | ETA ~ 1037.7 min
Ollama progress: 975/11923 | checkpoint saved | ETA ~ 1034.7 min
Ollama progress: 1000/11923 | checkpoint saved | ETA ~ 1031.7 min
Ollama progress: 1025/11923 | checkpoint saved | ETA ~ 1028.2 min
Ollama progress: 1050/11923 | checkpoint saved | ETA ~ 1024.7 min
Ollama progress: 1075/11923 | checkpoint saved | ETA ~ 1021.7 min
Ollama progress: 1100/11923 | checkpoint saved | ETA ~ 1019.1 min
Ollama progress: 1125/11923 | checkpoint saved | ETA ~ 1015.3 min
Ollama progress: 1150/11923 | checkpoint saved | ETA ~ 1012.7 min
Ollama progress: 1175/11923 | checkpoint saved | ETA ~ 1009.6 min
Ollama progress: 1200/11923 | checkpoint saved | ETA ~ 1006.2 min
Ollama progress: 1225/11923 | checkpoint saved | ETA ~ 1004.7 min
Ollama progress: 1250/11923 | checkpoint saved | ETA ~ 1002.3 min
Ollama progress: 1275/11923 | checkpoint saved | ETA ~ 999.6 min
Ollama progress: 1300/11923 | checkpoint saved | ETA ~ 996.8 min
Ollama progress: 1325/11923 | checkpoint saved | ETA ~ 994.0 min
Ollama progress: 1350/11923 | checkpoint saved | ETA ~ 990.7 min
Ollama progress: 1375/11923 | checkpoint saved | ETA ~ 987.6 min
Ollama progress: 1400/11923 | checkpoint saved | ETA ~ 984.5 min
Ollama progress: 1425/11923 | checkpoint saved | ETA ~ 982.2 min
Ollama progress: 1450/11923 | checkpoint saved | ETA ~ 979.1 min
Ollama progress: 1475/11923 | checkpoint saved | ETA ~ 977.6 min
Ollama progress: 1500/11923 | checkpoint saved | ETA ~ 975.1 min
Ollama progress: 1525/11923 | checkpoint saved | ETA ~ 972.1 min
Ollama progress: 1550/11923 | checkpoint saved | ETA ~ 969.2 min
Ollama progress: 1575/11923 | checkpoint saved | ETA ~ 967.5 min
Ollama progress: 1600/11923 | checkpoint saved | ETA ~ 965.4 min
Ollama progress: 1625/11923 | checkpoint saved | ETA ~ 962.8 min
Ollama progress: 1650/11923 | checkpoint saved | ETA ~ 960.3 min
Ollama progress: 1675/11923 | checkpoint saved | ETA ~ 957.8 min
Ollama progress: 1700/11923 | checkpoint saved | ETA ~ 954.9 min
Ollama progress: 1725/11923 | checkpoint saved | ETA ~ 952.0 min
Ollama progress: 1750/11923 | checkpoint saved | ETA ~ 949.7 min
Ollama progress: 1775/11923 | checkpoint saved | ETA ~ 946.8 min
Ollama progress: 1800/11923 | checkpoint saved | ETA ~ 943.9 min
Ollama progress: 1825/11923 | checkpoint saved | ETA ~ 941.2 min
Ollama progress: 1850/11923 | checkpoint saved | ETA ~ 938.2 min
Ollama progress: 1875/11923 | checkpoint saved | ETA ~ 935.4 min
Ollama progress: 1900/11923 | checkpoint saved | ETA ~ 932.5 min
Ollama progress: 1925/11923 | checkpoint saved | ETA ~ 930.1 min
Ollama progress: 1950/11923 | checkpoint saved | ETA ~ 927.6 min
Ollama progress: 1975/11923 | checkpoint saved | ETA ~ 924.9 min
Ollama progress: 2000/11923 | checkpoint saved | ETA ~ 922.5 min
Ollama progress: 2025/11923 | checkpoint saved | ETA ~ 919.7 min
Ollama progress: 2050/11923 | checkpoint saved | ETA ~ 917.0 min
Ollama progress: 2075/11923 | checkpoint saved | ETA ~ 914.6 min
Ollama progress: 2100/11923 | checkpoint saved | ETA ~ 912.0 min
Ollama progress: 2125/11923 | checkpoint saved | ETA ~ 909.6 min
Ollama progress: 2150/11923 | checkpoint saved | ETA ~ 906.6 min
Ollama progress: 2175/11923 | checkpoint saved | ETA ~ 904.3 min
Ollama progress: 2200/11923 | checkpoint saved | ETA ~ 901.9 min
Ollama progress: 2225/11923 | checkpoint saved | ETA ~ 899.1 min
Ollama progress: 2250/11923 | checkpoint saved | ETA ~ 896.2 min
Ollama progress: 2275/11923 | checkpoint saved | ETA ~ 894.0 min
Ollama progress: 2300/11923 | checkpoint saved | ETA ~ 891.4 min
Ollama progress: 2325/11923 | checkpoint saved | ETA ~ 888.9 min
Ollama progress: 2350/11923 | checkpoint saved | ETA ~ 886.5 min
Ollama progress: 2375/11923 | checkpoint saved | ETA ~ 883.9 min
Ollama progress: 2400/11923 | checkpoint saved | ETA ~ 881.1 min
Ollama progress: 2425/11923 | checkpoint saved | ETA ~ 878.5 min
Ollama progress: 2450/11923 | checkpoint saved | ETA ~ 875.5 min
Ollama progress: 2475/11923 | checkpoint saved | ETA ~ 873.6 min
Ollama progress: 2500/11923 | checkpoint saved | ETA ~ 870.9 min
Ollama progress: 2525/11923 | checkpoint saved | ETA ~ 868.4 min
Ollama progress: 2550/11923 | checkpoint saved | ETA ~ 865.8 min
Ollama progress: 2575/11923 | checkpoint saved | ETA ~ 863.3 min
Ollama progress: 2600/11923 | checkpoint saved | ETA ~ 860.8 min
Ollama progress: 2625/11923 | checkpoint saved | ETA ~ 858.1 min
Ollama progress: 2650/11923 | checkpoint saved | ETA ~ 855.9 min
Ollama progress: 2675/11923 | checkpoint saved | ETA ~ 853.6 min
Ollama progress: 2700/11923 | checkpoint saved | ETA ~ 851.5 min
Ollama progress: 2725/11923 | checkpoint saved | ETA ~ 849.6 min
Ollama progress: 2750/11923 | checkpoint saved | ETA ~ 847.5 min
Ollama progress: 2775/11923 | checkpoint saved | ETA ~ 844.9 min
Ollama progress: 2800/11923 | checkpoint saved | ETA ~ 842.8 min
Ollama progress: 2825/11923 | checkpoint saved | ETA ~ 840.7 min
Ollama progress: 2850/11923 | checkpoint saved | ETA ~ 838.3 min
Ollama progress: 2875/11923 | checkpoint saved | ETA ~ 836.2 min
Ollama progress: 2900/11923 | checkpoint saved | ETA ~ 834.1 min
Ollama progress: 2925/11923 | checkpoint saved | ETA ~ 831.8 min
Ollama progress: 2950/11923 | checkpoint saved | ETA ~ 829.2 min
Ollama progress: 2975/11923 | checkpoint saved | ETA ~ 826.9 min
Ollama progress: 3000/11923 | checkpoint saved | ETA ~ 824.4 min
Ollama progress: 3025/11923 | checkpoint saved | ETA ~ 822.0 min
Ollama progress: 3050/11923 | checkpoint saved | ETA ~ 819.4 min
Ollama progress: 3075/11923 | checkpoint saved | ETA ~ 816.9 min
Ollama progress: 3100/11923 | checkpoint saved | ETA ~ 814.6 min
Ollama progress: 3125/11923 | checkpoint saved | ETA ~ 812.2 min
Ollama progress: 3150/11923 | checkpoint saved | ETA ~ 809.7 min
Ollama progress: 3175/11923 | checkpoint saved | ETA ~ 807.3 min
Ollama progress: 3200/11923 | checkpoint saved | ETA ~ 805.0 min
Ollama progress: 3225/11923 | checkpoint saved | ETA ~ 803.0 min
Ollama progress: 3250/11923 | checkpoint saved | ETA ~ 800.6 min
Ollama progress: 3275/11923 | checkpoint saved | ETA ~ 798.2 min
Ollama progress: 3300/11923 | checkpoint saved | ETA ~ 795.9 min
Ollama progress: 3325/11923 | checkpoint saved | ETA ~ 793.5 min
Ollama progress: 3350/11923 | checkpoint saved | ETA ~ 791.0 min
Ollama progress: 3375/11923 | checkpoint saved | ETA ~ 788.8 min
Ollama progress: 3400/11923 | checkpoint saved | ETA ~ 786.4 min
Ollama progress: 3425/11923 | checkpoint saved | ETA ~ 784.1 min
Ollama progress: 3450/11923 | checkpoint saved | ETA ~ 781.7 min
Ollama progress: 3475/11923 | checkpoint saved | ETA ~ 779.3 min
Ollama progress: 3500/11923 | checkpoint saved | ETA ~ 777.0 min
Ollama progress: 3525/11923 | checkpoint saved | ETA ~ 774.8 min
Ollama progress: 3550/11923 | checkpoint saved | ETA ~ 772.5 min
Ollama progress: 3575/11923 | checkpoint saved | ETA ~ 770.1 min
Ollama progress: 3600/11923 | checkpoint saved | ETA ~ 767.9 min
Ollama progress: 3625/11923 | checkpoint saved | ETA ~ 765.9 min
Ollama progress: 3650/11923 | checkpoint saved | ETA ~ 763.5 min
Ollama progress: 3675/11923 | checkpoint saved | ETA ~ 761.3 min
Ollama progress: 3700/11923 | checkpoint saved | ETA ~ 759.0 min
Ollama progress: 3725/11923 | checkpoint saved | ETA ~ 756.6 min
Ollama progress: 3750/11923 | checkpoint saved | ETA ~ 754.1 min
Ollama progress: 3775/11923 | checkpoint saved | ETA ~ 751.9 min
Ollama progress: 3800/11923 | checkpoint saved | ETA ~ 749.5 min
Ollama progress: 3825/11923 | checkpoint saved | ETA ~ 748.1 min
Ollama progress: 3850/11923 | checkpoint saved | ETA ~ 746.5 min
Ollama progress: 3875/11923 | checkpoint saved | ETA ~ 744.9 min
Ollama progress: 3900/11923 | checkpoint saved | ETA ~ 743.6 min
Ollama progress: 3925/11923 | checkpoint saved | ETA ~ 741.8 min
Ollama progress: 3950/11923 | checkpoint saved | ETA ~ 740.5 min
Ollama progress: 3975/11923 | checkpoint saved | ETA ~ 739.2 min
Ollama progress: 4000/11923 | checkpoint saved | ETA ~ 737.5 min
Ollama progress: 4025/11923 | checkpoint saved | ETA ~ 735.9 min
Ollama progress: 4050/11923 | checkpoint saved | ETA ~ 734.4 min
Ollama progress: 4075/11923 | checkpoint saved | ETA ~ 732.9 min
Ollama progress: 4100/11923 | checkpoint saved | ETA ~ 731.4 min
Ollama progress: 4125/11923 | checkpoint saved | ETA ~ 729.6 min
Ollama progress: 4150/11923 | checkpoint saved | ETA ~ 727.9 min
Ollama progress: 4175/11923 | checkpoint saved | ETA ~ 726.2 min
Ollama progress: 4200/11923 | checkpoint saved | ETA ~ 724.6 min
Ollama progress: 4225/11923 | checkpoint saved | ETA ~ 722.7 min
Ollama progress: 4250/11923 | checkpoint saved | ETA ~ 720.8 min
Ollama progress: 4275/11923 | checkpoint saved | ETA ~ 719.0 min
Ollama progress: 4300/11923 | checkpoint saved | ETA ~ 717.3 min
Ollama progress: 4325/11923 | checkpoint saved | ETA ~ 715.6 min
Ollama progress: 4350/11923 | checkpoint saved | ETA ~ 713.6 min
Ollama progress: 4375/11923 | checkpoint saved | ETA ~ 712.0 min
Ollama progress: 4400/11923 | checkpoint saved | ETA ~ 710.2 min
Ollama progress: 4425/11923 | checkpoint saved | ETA ~ 708.3 min
Ollama progress: 4450/11923 | checkpoint saved | ETA ~ 706.6 min
Ollama progress: 4475/11923 | checkpoint saved | ETA ~ 704.7 min
Ollama progress: 4500/11923 | checkpoint saved | ETA ~ 703.0 min
Ollama progress: 4525/11923 | checkpoint saved | ETA ~ 701.2 min
Ollama progress: 4550/11923 | checkpoint saved | ETA ~ 698.9 min
Ollama progress: 4575/11923 | checkpoint saved | ETA ~ 696.7 min
Ollama progress: 4600/11923 | checkpoint saved | ETA ~ 694.4 min
Ollama progress: 4625/11923 | checkpoint saved | ETA ~ 692.3 min
Ollama progress: 4650/11923 | checkpoint saved | ETA ~ 690.0 min
Ollama progress: 4675/11923 | checkpoint saved | ETA ~ 688.2 min
Ollama progress: 4700/11923 | checkpoint saved | ETA ~ 686.2 min
Ollama progress: 4725/11923 | checkpoint saved | ETA ~ 684.0 min
Ollama progress: 4750/11923 | checkpoint saved | ETA ~ 681.5 min
Ollama progress: 4775/11923 | checkpoint saved | ETA ~ 679.1 min
Ollama progress: 4800/11923 | checkpoint saved | ETA ~ 676.7 min
Ollama progress: 4825/11923 | checkpoint saved | ETA ~ 674.6 min
Ollama progress: 4850/11923 | checkpoint saved | ETA ~ 672.6 min
Ollama progress: 4875/11923 | checkpoint saved | ETA ~ 670.8 min
Ollama progress: 4900/11923 | checkpoint saved | ETA ~ 668.7 min
Ollama progress: 4925/11923 | checkpoint saved | ETA ~ 666.7 min
Ollama progress: 4950/11923 | checkpoint saved | ETA ~ 664.7 min
Ollama progress: 4975/11923 | checkpoint saved | ETA ~ 662.7 min
Ollama progress: 5000/11923 | checkpoint saved | ETA ~ 660.3 min
Ollama progress: 5025/11923 | checkpoint saved | ETA ~ 658.0 min
Ollama progress: 5050/11923 | checkpoint saved | ETA ~ 655.6 min
Ollama progress: 5075/11923 | checkpoint saved | ETA ~ 653.2 min
Ollama progress: 5100/11923 | checkpoint saved | ETA ~ 650.8 min
Ollama progress: 5125/11923 | checkpoint saved | ETA ~ 648.6 min
Ollama progress: 5150/11923 | checkpoint saved | ETA ~ 646.4 min
Ollama progress: 5175/11923 | checkpoint saved | ETA ~ 644.2 min
Ollama progress: 5200/11923 | checkpoint saved | ETA ~ 642.1 min
Ollama progress: 5225/11923 | checkpoint saved | ETA ~ 639.8 min
Ollama progress: 5250/11923 | checkpoint saved | ETA ~ 637.4 min
Ollama progress: 5275/11923 | checkpoint saved | ETA ~ 634.8 min
Ollama progress: 5300/11923 | checkpoint saved | ETA ~ 632.5 min
Ollama progress: 5325/11923 | checkpoint saved | ETA ~ 630.3 min
Ollama progress: 5350/11923 | checkpoint saved | ETA ~ 628.4 min
Ollama progress: 5375/11923 | checkpoint saved | ETA ~ 626.2 min
Ollama progress: 5400/11923 | checkpoint saved | ETA ~ 623.9 min
Ollama progress: 5425/11923 | checkpoint saved | ETA ~ 621.4 min
Ollama progress: 5450/11923 | checkpoint saved | ETA ~ 619.0 min
Ollama progress: 5475/11923 | checkpoint saved | ETA ~ 616.8 min
Ollama progress: 5500/11923 | checkpoint saved | ETA ~ 614.6 min
Ollama progress: 5525/11923 | checkpoint saved | ETA ~ 612.2 min
Ollama progress: 5550/11923 | checkpoint saved | ETA ~ 609.7 min
Ollama progress: 5575/11923 | checkpoint saved | ETA ~ 607.2 min
Ollama progress: 5600/11923 | checkpoint saved | ETA ~ 605.2 min
Ollama progress: 5625/11923 | checkpoint saved | ETA ~ 602.7 min
Ollama progress: 5650/11923 | checkpoint saved | ETA ~ 600.3 min
Ollama progress: 5675/11923 | checkpoint saved | ETA ~ 597.8 min
Ollama progress: 5700/11923 | checkpoint saved | ETA ~ 595.7 min
Ollama progress: 5725/11923 | checkpoint saved | ETA ~ 593.6 min
Ollama progress: 5750/11923 | checkpoint saved | ETA ~ 591.4 min
Ollama progress: 5775/11923 | checkpoint saved | ETA ~ 589.4 min
Ollama progress: 5800/11923 | checkpoint saved | ETA ~ 587.3 min
Ollama progress: 5825/11923 | checkpoint saved | ETA ~ 585.2 min
Ollama progress: 5850/11923 | checkpoint saved | ETA ~ 583.0 min
Ollama progress: 5875/11923 | checkpoint saved | ETA ~ 580.8 min
Ollama progress: 5900/11923 | checkpoint saved | ETA ~ 578.8 min
Ollama progress: 5925/11923 | checkpoint saved | ETA ~ 576.8 min
Ollama progress: 5950/11923 | checkpoint saved | ETA ~ 574.7 min
Ollama progress: 5975/11923 | checkpoint saved | ETA ~ 572.5 min
Ollama progress: 6000/11923 | checkpoint saved | ETA ~ 570.3 min
Ollama progress: 6025/11923 | checkpoint saved | ETA ~ 568.2 min
Ollama progress: 6050/11923 | checkpoint saved | ETA ~ 566.3 min
Ollama progress: 6075/11923 | checkpoint saved | ETA ~ 564.1 min
Ollama progress: 6100/11923 | checkpoint saved | ETA ~ 562.0 min
Ollama progress: 6125/11923 | checkpoint saved | ETA ~ 560.2 min
Ollama progress: 6150/11923 | checkpoint saved | ETA ~ 558.3 min
Ollama progress: 6175/11923 | checkpoint saved | ETA ~ 556.3 min
Ollama progress: 6200/11923 | checkpoint saved | ETA ~ 554.3 min
Ollama progress: 6225/11923 | checkpoint saved | ETA ~ 552.3 min
Ollama progress: 6250/11923 | checkpoint saved | ETA ~ 550.2 min
Ollama progress: 6275/11923 | checkpoint saved | ETA ~ 548.2 min
Ollama progress: 6300/11923 | checkpoint saved | ETA ~ 546.2 min
Ollama progress: 6325/11923 | checkpoint saved | ETA ~ 544.1 min
Ollama progress: 6350/11923 | checkpoint saved | ETA ~ 542.0 min
Ollama progress: 6375/11923 | checkpoint saved | ETA ~ 539.8 min
Ollama progress: 6400/11923 | checkpoint saved | ETA ~ 537.6 min
Ollama progress: 6425/11923 | checkpoint saved | ETA ~ 535.2 min
Ollama progress: 6450/11923 | checkpoint saved | ETA ~ 532.7 min
Ollama progress: 6475/11923 | checkpoint saved | ETA ~ 530.1 min
Ollama progress: 6500/11923 | checkpoint saved | ETA ~ 527.6 min
Ollama progress: 6525/11923 | checkpoint saved | ETA ~ 525.0 min
Ollama progress: 6550/11923 | checkpoint saved | ETA ~ 522.5 min
Ollama progress: 6575/11923 | checkpoint saved | ETA ~ 519.9 min
Ollama progress: 6600/11923 | checkpoint saved | ETA ~ 517.4 min
Ollama progress: 6625/11923 | checkpoint saved | ETA ~ 514.9 min
Ollama progress: 6650/11923 | checkpoint saved | ETA ~ 512.8 min
Ollama progress: 6675/11923 | checkpoint saved | ETA ~ 510.5 min
Ollama progress: 6700/11923 | checkpoint saved | ETA ~ 508.2 min
Ollama progress: 6725/11923 | checkpoint saved | ETA ~ 505.9 min
Ollama progress: 6750/11923 | checkpoint saved | ETA ~ 503.5 min
Ollama progress: 6775/11923 | checkpoint saved | ETA ~ 500.9 min
Ollama progress: 6800/11923 | checkpoint saved | ETA ~ 498.3 min
Ollama progress: 6825/11923 | checkpoint saved | ETA ~ 495.8 min
Ollama progress: 6850/11923 | checkpoint saved | ETA ~ 493.3 min
Ollama progress: 6875/11923 | checkpoint saved | ETA ~ 490.8 min
Ollama progress: 6900/11923 | checkpoint saved | ETA ~ 488.2 min
Ollama progress: 6925/11923 | checkpoint saved | ETA ~ 485.7 min
Ollama progress: 6950/11923 | checkpoint saved | ETA ~ 483.2 min
Ollama progress: 6975/11923 | checkpoint saved | ETA ~ 480.8 min
Ollama progress: 7000/11923 | checkpoint saved | ETA ~ 478.4 min
Ollama progress: 7025/11923 | checkpoint saved | ETA ~ 475.9 min
Ollama progress: 7050/11923 | checkpoint saved | ETA ~ 473.4 min
Ollama progress: 7075/11923 | checkpoint saved | ETA ~ 470.9 min
Ollama progress: 7100/11923 | checkpoint saved | ETA ~ 468.4 min
Ollama progress: 7125/11923 | checkpoint saved | ETA ~ 465.8 min
Ollama progress: 7150/11923 | checkpoint saved | ETA ~ 463.4 min
Ollama progress: 7175/11923 | checkpoint saved | ETA ~ 460.8 min
Ollama progress: 7200/11923 | checkpoint saved | ETA ~ 458.3 min
Ollama progress: 7225/11923 | checkpoint saved | ETA ~ 455.7 min
Ollama progress: 7250/11923 | checkpoint saved | ETA ~ 453.3 min
Ollama progress: 7275/11923 | checkpoint saved | ETA ~ 450.8 min
Ollama progress: 7300/11923 | checkpoint saved | ETA ~ 448.2 min
Ollama progress: 7325/11923 | checkpoint saved | ETA ~ 445.7 min
Ollama progress: 7350/11923 | checkpoint saved | ETA ~ 443.2 min
Ollama progress: 7375/11923 | checkpoint saved | ETA ~ 440.8 min
Ollama progress: 7400/11923 | checkpoint saved | ETA ~ 438.3 min
Ollama progress: 7425/11923 | checkpoint saved | ETA ~ 435.8 min
Ollama progress: 7450/11923 | checkpoint saved | ETA ~ 433.4 min
Ollama progress: 7475/11923 | checkpoint saved | ETA ~ 430.9 min
Ollama progress: 7500/11923 | checkpoint saved | ETA ~ 428.4 min
Ollama progress: 7525/11923 | checkpoint saved | ETA ~ 425.9 min
Ollama progress: 7550/11923 | checkpoint saved | ETA ~ 423.4 min
Ollama progress: 7575/11923 | checkpoint saved | ETA ~ 420.9 min
Ollama progress: 7600/11923 | checkpoint saved | ETA ~ 418.4 min
Ollama progress: 7625/11923 | checkpoint saved | ETA ~ 415.9 min
Ollama progress: 7650/11923 | checkpoint saved | ETA ~ 413.5 min
Ollama progress: 7675/11923 | checkpoint saved | ETA ~ 410.9 min

,tweet,y_test_label,ollama_prediction,is_match
0,today tomorrow try move mountains cross fingers,other_cyberbullying,not_cyberbullying,False
1,typa girl bullied lesbians high school,age,gender,False
2,cool woman gave directions polling place whose...,age,gender,False
3,need teach version quran terrorists killing pe...,religion,religion,True
4,rome destroy coliseum roman forum every buildi...,religion,religion,True
5,try hide jihadi propaganda know hell gys specl...,religion,religion,True
6,city college,not_cyberbullying,not_cyberbullying,True
7,pepperidge farm remembers,other_cyberbullying,not_cyberbullying,False
8,added feminazi white knight professional victi...,other_cyberbullying,gender,False
9,blm something know muslim leaders record stati...,religion,religion,True
10,life better sex know sex know someone dying se...,not_cyberbullying,not_cyberbullying,True
11,bullied high school girl fat karma really come...,age,gender,False
12,always ignore people get mixed always call “se...,gender,gender,True
13,lot people cell phones one years used idea dis...,other_cyberbullying,not_cyberbullying,False
14,yours mine enforced men jail visitation these ...,gender,not_cyberbullying,False
15,fucking love her hot shit,not_cyberbullying,not_cyberbullying,True
16,gay marriage think rape ever joke rape chances...,gender,gender,True
17,uscirf biased blindfolded islamic terrorism ri...,religion,religion,True
18,liked video httptcoqigeerlzpj rape fraud femin...,gender,other_cyberbullying,False
19,ummm what even muslim nation y’all act like ai...,religion,religion,True

Done. Collected 11923 predictions from model: qwen2.5:7b-instruct
Total exact label matches: 5277/11923
Checkpoint file: Artifacts\ollama_checkpoint_qwen2.5_7b-instruct.pkl
Predictions artifact: Artifacts\ollama_predictions_qwen2.5_7b-instruct.pkl

#### **Evaluation**

In [18]:
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, classification_report

# Ensure y_eval is integer index array and lengths match predictions.
y_eval_idx = np.asarray(y_eval).astype(int)
ollama_pred_idx = np.asarray(ollama_pred_ids).astype(int)

if len(y_eval_idx) != len(ollama_pred_idx):
    raise ValueError(
        f"Length mismatch: y_eval has {len(y_eval_idx)} rows, ollama_pred has {len(ollama_pred_idx)} rows"
    )

# Keep readable labels and index columns for inspection.
ollama_pred_df["true_label_idx"] = y_eval_idx
ollama_pred_df["ollama_pred_idx"] = ollama_pred_idx
display(ollama_pred_df.head(10))

p, r, f1, support = precision_recall_fscore_support(
    y_eval_idx,
    ollama_pred_idx,
    average="weighted",
    zero_division=0,
 )

ollama_metrics = {
    "Accuracy": accuracy_score(y_eval_idx, ollama_pred_idx),
    "Precision": p,
    "Recall": r,
    "F1-Score": f1,
    "Support": int(len(y_eval_idx)),
}

ollama_metrics_df = pd.DataFrame(ollama_metrics, index=[OLLAMA_MODEL]).T
display(ollama_metrics_df)

print("\nLLM classification report:\n")
print(
    classification_report(
        y_eval_idx,
        ollama_pred_idx,
        target_names=class_names_list,
        zero_division=0,
    )
)

,tweet,y_test_label,ollama_prediction,is_match,true_label_idx,ollama_pred_idx
0,today tomorrow try move mountains cross fingers,other_cyberbullying,not_cyberbullying,False,4,3
1,typa girl bullied lesbians high school,age,gender,False,0,2
2,cool woman gave directions polling place whose...,age,gender,False,0,2
3,need teach version quran terrorists killing pe...,religion,religion,True,5,5
4,rome destroy coliseum roman forum every buildi...,religion,religion,True,5,5
5,try hide jihadi propaganda know hell gys specl...,religion,religion,True,5,5
6,city college,not_cyberbullying,not_cyberbullying,True,3,3
7,pepperidge farm remembers,other_cyberbullying,not_cyberbullying,False,4,3
8,added feminazi white knight professional victi...,other_cyberbullying,gender,False,4,2
9,blm something know muslim leaders record stati...,religion,religion,True,5,5

           qwen2.5:7b-instruct
Accuracy              0.442590
Precision             0.524460
Recall                0.442590
F1-Score              0.428401
Support           11923.000000

LLM classification report:

                     precision    recall  f1-score   support

                age       0.51      0.02      0.04      1952
          ethnicity       0.79      0.42      0.55      1995
             gender       0.48      0.44      0.46      1952
  not_cyberbullying       0.39      0.69      0.50      2040
other_cyberbullying       0.13      0.23      0.17      2006
           religion       0.85      0.85      0.85      1978

           accuracy                           0.44     11923
          macro avg       0.53      0.44      0.43     11923
       weighted avg       0.52      0.44      0.43     11923

### **Zero-shot Classifier Models**

#### **Predictions**

In [ ]:
# Additional zero-shot benchmark across 3 models (BART + ModernBERT + DeBERTa-v3)
import re
import time
import numpy as np
import pandas as pd
import joblib
from pathlib import Path
from transformers import pipeline
import torch
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

try:
    from datasets import Dataset
    from transformers.pipelines.pt_utils import KeyDataset
except ImportError as e:
    raise ImportError(
        "datasets is required for efficient GPU batching. Install with: pip install datasets"
    ) from e

# ---------------------------------------------------------
# Models to benchmark (edit these IDs if you want variants)
# ---------------------------------------------------------
ZS_MODELS = [
    "facebook/bart-large-mnli",
    "MoritzLaurer/ModernBERT-large-zeroshot-v2.0",
    "MoritzLaurer/deberta-v3-large-zeroshot-v2.0",
]

# Set to None to use all tweets. Set an int (e.g., 1000) for a quick sample run.
MAX_ZS_CASES = None

ZS_BATCH_SIZE = 16
ZS_HYPOTHESIS_TEMPLATE = "This tweet belongs to the {} category."
ZS_CHECKPOINT_EVERY = 1000
ZS_RESUME_FROM_CHECKPOINT = True
ZS_RESET_CHECKPOINT = False

# Use CUDA when available; otherwise use CPU.
ZS_DEVICE = 0 if torch.cuda.is_available() else -1
print(f"Multi-model zero-shot device: {'cuda' if ZS_DEVICE == 0 else 'cpu'}")

# Reuse prepared split when available.
if "x_eval" not in globals() or "y_eval" not in globals():
    x_eval = list(x_test)
    y_eval = np.asarray(y_test)

if "class_names_list" not in globals():
    class_names_list = [str(x) for x in list(class_names)]

candidate_labels = list(class_names_list)
label_to_id = {label: i for i, label in enumerate(candidate_labels)}
if len(candidate_labels) == 0:
    raise ValueError("candidate_labels is empty. Please ensure class_names is loaded.")

# Reuse existing artifacts directory if set; otherwise default to ./Artifacts.
if "artifacts_dir" in globals():
    artifacts_dir_multi = Path(artifacts_dir)
else:
    artifacts_dir_multi = Path(r"./Artifacts")
artifacts_dir_multi.mkdir(parents=True, exist_ok=True)

def _sanitize_text(t) -> str:
    text = "" if t is None else str(t)
    text = text.strip()
    return text if text else "[EMPTY_TWEET]"

# Optional quick subset for all 3 models.
if MAX_ZS_CASES is None:
    x_eval_run = list(x_eval)
    y_eval_run = np.asarray(y_eval)
else:
    x_eval_run = list(x_eval)[: int(MAX_ZS_CASES)]
    y_eval_run = np.asarray(y_eval)[: int(MAX_ZS_CASES)]

x_eval_text = [_sanitize_text(t) for t in x_eval_run]
y_eval_idx = np.asarray(y_eval_run).astype(int)
total = len(x_eval_text)
if total == 0:
    raise ValueError("x_eval has no samples to predict.")

print(f"Running multi-model zero-shot on {total} tweets (MAX_ZS_CASES={MAX_ZS_CASES})")

def _run_zeroshot_model(model_name: str):
    safe_name = re.sub(r"[^a-zA-Z0-9_.-]", "_", model_name)
    size_tag = f"_{total}"
    checkpoint_path = artifacts_dir_multi / f"nli_checkpoint_{safe_name}{size_tag}.pkl"
    predictions_path = artifacts_dir_multi / f"nli_predictions_{safe_name}{size_tag}.pkl"

    if ZS_RESET_CHECKPOINT and checkpoint_path.exists():
        checkpoint_path.unlink()
        print(f"Deleted old checkpoint: {checkpoint_path}")

    pred_ids_list = []
    pred_labels = []
    pred_rows = []
    start_index = 0

    if ZS_RESUME_FROM_CHECKPOINT and checkpoint_path.exists():
        state = joblib.load(checkpoint_path)
        same_model = state.get("model") == model_name
        same_size = int(state.get("x_eval_size", -1)) == total
        same_labels = state.get("candidate_labels", []) == candidate_labels
        if same_model and same_size and same_labels:
            pred_ids_list = list(state.get("pred_ids", []))
            pred_labels = list(state.get("pred_labels", []))
            pred_rows = list(state.get("pred_rows", []))
            start_index = int(state.get("next_index", len(pred_labels)))
            start_index = max(0, min(start_index, total))
            print(f"Resumed checkpoint for {model_name}: {len(pred_labels)} predictions")
        else:
            print(f"Skipped mismatched checkpoint for {model_name}")

    def _save_ckpt(next_index: int, pred_ids, labels, rows):
        state = {
            "model": model_name,
            "candidate_labels": candidate_labels,
            "x_eval_size": total,
            "next_index": int(next_index),
            "pred_ids": list(pred_ids),
            "pred_labels": list(labels),
            "pred_rows": list(rows),
            "saved_at_unix": time.time(),
        }
        joblib.dump(state, checkpoint_path)

    clf = pipeline(
        task="zero-shot-classification",
        model=model_name,
        device=ZS_DEVICE,
    )

    if start_index < total:
        run_dataset = Dataset.from_dict({"text": x_eval_text[start_index:]})
        keyed = KeyDataset(run_dataset, "text")
        t0 = time.time()
        for local_i, out in enumerate(
            clf(
                keyed,
                candidate_labels=candidate_labels,
                multi_label=False,
                hypothesis_template=ZS_HYPOTHESIS_TEMPLATE,
                batch_size=ZS_BATCH_SIZE,
                truncation=True,
            ),
            start=1,
        ):
            pred_label = out["labels"][0]
            pred_id = int(label_to_id[pred_label])
            idx = start_index + local_i - 1

            pred_labels.append(pred_label)
            pred_ids_list.append(pred_id)
            pred_rows.append({
                "tweet": x_eval_text[idx],
                "y_test_label": candidate_labels[int(y_eval_idx[idx])],
                "nli_prediction": pred_label,
            })

            processed = start_index + local_i
            if (processed % ZS_CHECKPOINT_EVERY == 0) or (processed == total):
                _save_ckpt(processed, pred_ids_list, pred_labels, pred_rows)
                elapsed = time.time() - t0
                done_now = max(1, processed - start_index)
                eta_min = ((total - processed) * (elapsed / done_now)) / 60.0
                print(f"{model_name} progress: {processed}/{total} | checkpoint saved | ETA ~ {eta_min:.1f} min")

    if len(pred_labels) != total or len(pred_ids_list) != total:
        raise RuntimeError(
            f"Predictions incomplete for {model_name}: expected {total}, got labels={len(pred_labels)}, ids={len(pred_ids_list)}"
        )

    pred_ids = np.asarray(pred_ids_list, dtype=int)
    pred_df = pd.DataFrame(pred_rows)
    pred_df["is_match"] = pred_df["y_test_label"] == pred_df["nli_prediction"]

    joblib.dump(
        {
            "nli_pred_ids": pred_ids,
            "nli_pred_labels": pred_labels,
            "nli_pred_df": pred_df,
            "model": model_name,
            "candidate_labels": candidate_labels,
            "x_eval_size": total,
            "max_zs_cases": MAX_ZS_CASES,
        },
        predictions_path,
    )

    return pred_ids, pred_df, checkpoint_path, predictions_path

# ---------------------------------------------------------
# Run all 3 models and summarize
# ---------------------------------------------------------
multi_model_rows = []
multi_model_pred_store = {}

for model_name in ZS_MODELS:
    print("\n" + "=" * 100)
    print(f"Running zero-shot model: {model_name}")
    try:
        pred_ids, pred_df, ckpt_path, preds_path = _run_zeroshot_model(model_name)

        p, r, f1, _ = precision_recall_fscore_support(
            y_eval_idx,
            pred_ids,
            average="weighted",
            zero_division=0,
        )
        acc = accuracy_score(y_eval_idx, pred_ids)

        multi_model_rows.append({
            "model": model_name,
            "status": "ok",
            "accuracy": acc,
            "precision_weighted": p,
            "recall_weighted": r,
            "f1_weighted": f1,
            "support": int(len(y_eval_idx)),
            "checkpoint": str(ckpt_path),
            "predictions_artifact": str(preds_path),
            "error": "",
        })

        multi_model_pred_store[model_name] = {
            "pred_ids": pred_ids,
            "pred_df": pred_df,
            "checkpoint": str(ckpt_path),
            "predictions_artifact": str(preds_path),
        }

        print(f"Completed: {model_name}")
        print(f"Accuracy: {acc:.4f} | Precision: {p:.4f} | Recall: {r:.4f} | F1: {f1:.4f}")

    except Exception as e:
        multi_model_rows.append({
            "model": model_name,
            "status": "failed",
            "accuracy": np.nan,
            "precision_weighted": np.nan,
            "recall_weighted": np.nan,
            "f1_weighted": np.nan,
            "support": len(y_eval_idx),
            "checkpoint": "",
            "predictions_artifact": "",
            "error": str(e),
        })
        print(f"Failed: {model_name}")
        print(f"Error: {e}")

multi_model_metrics_df = pd.DataFrame(multi_model_rows)
display(multi_model_metrics_df)

# Save combined summary artifact
multi_summary_path = artifacts_dir_multi / f"nli_multi_model_summary_{total}.pkl"
joblib.dump(
    {
        "metrics_df": multi_model_metrics_df,
        "models": ZS_MODELS,
        "pred_store": multi_model_pred_store,
        "candidate_labels": candidate_labels,
        "x_eval_size": total,
        "max_zs_cases": MAX_ZS_CASES,
    },
    multi_summary_path,
 )
print(f"Saved multi-model summary: {multi_summary_path}")

Multi-model zero-shot device: cuda
Running multi-model zero-shot on 11923 tweets (MAX_ZS_CASES=None)

====================================================================================================
Running zero-shot model: facebook/bart-large-mnli

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json: 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/515 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

facebook/bart-large-mnli progress: 1000/11923 | checkpoint saved | ETA ~ 11.4 min
facebook/bart-large-mnli progress: 2000/11923 | checkpoint saved | ETA ~ 10.8 min
facebook/bart-large-mnli progress: 3000/11923 | checkpoint saved | ETA ~ 10.0 min
facebook/bart-large-mnli progress: 4000/11923 | checkpoint saved | ETA ~ 9.0 min
facebook/bart-large-mnli progress: 5000/11923 | checkpoint saved | ETA ~ 7.9 min
facebook/bart-large-mnli progress: 6000/11923 | checkpoint saved | ETA ~ 6.8 min
facebook/bart-large-mnli progress: 7000/11923 | checkpoint saved | ETA ~ 5.7 min
facebook/bart-large-mnli progress: 8000/11923 | checkpoint saved | ETA ~ 4.6 min
facebook/bart-large-mnli progress: 9000/11923 | checkpoint saved | ETA ~ 3.4 min
facebook/bart-large-mnli progress: 10000/11923 | checkpoint saved | ETA ~ 2.3 min
facebook/bart-large-mnli progress: 11000/11923 | checkpoint saved | ETA ~ 1.1 min
facebook/bart-large-mnli progress: 11923/11923 | checkpoint saved | ETA ~ 0.0 min
Completed: facebook/bart-large-mnli
Accuracy: 0.4465 | Precision: 0.4509 | Recall: 0.4465 | F1: 0.3994

====================================================================================================
Running zero-shot model: MoritzLaurer/ModernBERT-large-zeroshot-v2.0

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/792M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/174 [00:00<?, ?it/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/694 [00:00<?, ?B/s]

/usr/local/lib/python3.12/dist-packages/torch/_inductor/compile_fx.py:2900: UserWarning: Tesla T4 does not support bfloat16 compilation natively, skipping
  warnings.warn(
W0418 21:43:03.891000 5556 torch/_inductor/utils.py:1679] [1/0_1] Not enough SMs to use max_autotune_gemm mode
/usr/local/lib/python3.12/dist-packages/torch/_inductor/compile_fx.py:2900: UserWarning: Tesla T4 does not support bfloat16 compilation natively, skipping
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/torch/_inductor/compile_fx.py:2900: UserWarning: Tesla T4 does not support bfloat16 compilation natively, skipping
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/torch/_inductor/compile_fx.py:2900: UserWarning: Tesla T4 does not support bfloat16 compilation natively, skipping
  warnings.warn(

MoritzLaurer/ModernBERT-large-zeroshot-v2.0 progress: 1000/11923 | checkpoint saved | ETA ~ 19.2 min
MoritzLaurer/ModernBERT-large-zeroshot-v2.0 progress: 2000/11923 | checkpoint saved | ETA ~ 16.3 min
MoritzLaurer/ModernBERT-large-zeroshot-v2.0 progress: 3000/11923 | checkpoint saved | ETA ~ 14.3 min
MoritzLaurer/ModernBERT-large-zeroshot-v2.0 progress: 4000/11923 | checkpoint saved | ETA ~ 12.4 min
MoritzLaurer/ModernBERT-large-zeroshot-v2.0 progress: 5000/11923 | checkpoint saved | ETA ~ 10.7 min
MoritzLaurer/ModernBERT-large-zeroshot-v2.0 progress: 6000/11923 | checkpoint saved | ETA ~ 9.1 min
MoritzLaurer/ModernBERT-large-zeroshot-v2.0 progress: 7000/11923 | checkpoint saved | ETA ~ 7.6 min
MoritzLaurer/ModernBERT-large-zeroshot-v2.0 progress: 8000/11923 | checkpoint saved | ETA ~ 6.0 min
MoritzLaurer/ModernBERT-large-zeroshot-v2.0 progress: 9000/11923 | checkpoint saved | ETA ~ 4.5 min
MoritzLaurer/ModernBERT-large-zeroshot-v2.0 progress: 10000/11923 | checkpoint saved | ETA ~ 2.9 min
MoritzLaurer/ModernBERT-large-zeroshot-v2.0 progress: 11000/11923 | checkpoint saved | ETA ~ 1.4 min
MoritzLaurer/ModernBERT-large-zeroshot-v2.0 progress: 11923/11923 | checkpoint saved | ETA ~ 0.0 min
Completed: MoritzLaurer/ModernBERT-large-zeroshot-v2.0
Accuracy: 0.5704 | Precision: 0.6318 | Recall: 0.5704 | F1: 0.5509

====================================================================================================
Running zero-shot model: MoritzLaurer/deberta-v3-large-zeroshot-v2.0

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/870M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/394 [00:00<?, ?it/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

spm.model:   0%|          | 0.00/2.46M [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/23.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

MoritzLaurer/deberta-v3-large-zeroshot-v2.0 progress: 1000/11923 | checkpoint saved | ETA ~ 4.5 min
MoritzLaurer/deberta-v3-large-zeroshot-v2.0 progress: 2000/11923 | checkpoint saved | ETA ~ 4.0 min
MoritzLaurer/deberta-v3-large-zeroshot-v2.0 progress: 3000/11923 | checkpoint saved | ETA ~ 3.6 min
MoritzLaurer/deberta-v3-large-zeroshot-v2.0 progress: 4000/11923 | checkpoint saved | ETA ~ 3.1 min
MoritzLaurer/deberta-v3-large-zeroshot-v2.0 progress: 5000/11923 | checkpoint saved | ETA ~ 2.7 min
MoritzLaurer/deberta-v3-large-zeroshot-v2.0 progress: 6000/11923 | checkpoint saved | ETA ~ 2.3 min
MoritzLaurer/deberta-v3-large-zeroshot-v2.0 progress: 7000/11923 | checkpoint saved | ETA ~ 1.9 min
MoritzLaurer/deberta-v3-large-zeroshot-v2.0 progress: 8000/11923 | checkpoint saved | ETA ~ 1.5 min
MoritzLaurer/deberta-v3-large-zeroshot-v2.0 progress: 9000/11923 | checkpoint saved | ETA ~ 1.2 min
MoritzLaurer/deberta-v3-large-zeroshot-v2.0 progress: 10000/11923 | checkpoint saved | ETA ~ 0.8 min
MoritzLaurer/deberta-v3-large-zeroshot-v2.0 progress: 11000/11923 | checkpoint saved | ETA ~ 0.4 min
MoritzLaurer/deberta-v3-large-zeroshot-v2.0 progress: 11923/11923 | checkpoint saved | ETA ~ 0.0 min
Completed: MoritzLaurer/deberta-v3-large-zeroshot-v2.0
Accuracy: 0.5544 | Precision: 0.5942 | Recall: 0.5544 | F1: 0.5444

,model,status,accuracy,precision_weighted,recall_weighted,f1_weighted,support,checkpoint,predictions_artifact,error
0,facebook/bart-large-mnli,ok,0.446532,0.450896,0.446532,0.399407,11923,Artifacts/nli_checkpoint_facebook_bart-large-m...,Artifacts/nli_predictions_facebook_bart-large-...,
1,MoritzLaurer/ModernBERT-large-zeroshot-v2.0,ok,0.570410,0.631770,0.570410,0.550866,11923,Artifacts/nli_checkpoint_MoritzLaurer_ModernBE...,Artifacts/nli_predictions_MoritzLaurer_ModernB...,
2,MoritzLaurer/deberta-v3-large-zeroshot-v2.0,ok,0.554391,0.594193,0.554391,0.544434,11923,Artifacts/nli_checkpoint_MoritzLaurer_deberta-...,Artifacts/nli_predictions_MoritzLaurer_deberta...,

Saved multi-model summary: Artifacts/nli_multi_model_summary_11923.pkl

#### **Evaluation**
Print weighted evaluation metrics and full classification report for each successfully-run zero-shot model.

In [ ]:
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, classification_report

if "multi_model_pred_store" not in globals():
    raise ValueError("multi_model_pred_store not found. Run the multi-model predictions cell first.")

if "y_eval_idx" not in globals() or "class_names_list" not in globals():
    raise ValueError("y_eval_idx/class_names_list not found. Run the zero-shot cells above first.")

eval_rows = []

for model_name, payload in multi_model_pred_store.items():
    pred_ids = np.asarray(payload.get("pred_ids", []), dtype=int)
    if len(pred_ids) != len(y_eval_idx):
        print(f"Skipping {model_name}: length mismatch ({len(pred_ids)} vs {len(y_eval_idx)})")
        continue

    p, r, f1, _ = precision_recall_fscore_support(
        y_eval_idx, pred_ids, average="weighted", zero_division=0
    )
    acc = accuracy_score(y_eval_idx, pred_ids)

    eval_rows.append({
        "Model": model_name,
        "Accuracy": acc,
        "Precision": p,
        "Recall": r,
        "F1-Score": f1,
        "Support": int(len(y_eval_idx)),
    })

eval_df = pd.DataFrame(eval_rows)
if not eval_df.empty:
    display(eval_df.set_index("Model"))
else:
    print("No successful model predictions available to evaluate.")

for model_name, payload in multi_model_pred_store.items():
    pred_ids = np.asarray(payload.get("pred_ids", []), dtype=int)
    if len(pred_ids) != len(y_eval_idx):
        continue

    print("\n" + "=" * 100)
    print(f"Classification report for: {model_name}")
    print(
        classification_report(
            y_eval_idx,
            pred_ids,
            target_names=class_names_list,
            zero_division=0,
        )
    )

,Accuracy,Precision,Recall,F1-Score,Support
Model,,,,,
facebook/bart-large-mnli,0.446532,0.450896,0.446532,0.399407,11923
MoritzLaurer/ModernBERT-large-zeroshot-v2.0,0.570410,0.631770,0.570410,0.550866,11923
MoritzLaurer/deberta-v3-large-zeroshot-v2.0,0.554391,0.594193,0.554391,0.544434,11923

====================================================================================================
Classification report for: facebook/bart-large-mnli
                     precision    recall  f1-score   support

                age       0.35      0.61      0.44      1952
          ethnicity       0.52      0.83      0.64      1995
             gender       0.38      0.63      0.48      1952
  not_cyberbullying       0.27      0.08      0.12      2040
other_cyberbullying       0.34      0.07      0.11      2006
           religion       0.86      0.49      0.62      1978

           accuracy                           0.45     11923
          macro avg       0.45      0.45      0.40     11923
       weighted avg       0.45      0.45      0.40     11923


====================================================================================================
Classification report for: MoritzLaurer/ModernBERT-large-zeroshot-v2.0
                     precision    recall  f1-score   support

                age       0.79      0.23      0.35      1952
          ethnicity       0.77      0.81      0.79      1995
             gender       0.50      0.76      0.60      1952
  not_cyberbullying       0.38      0.73      0.50      2040
other_cyberbullying       0.47      0.20      0.28      2006
           religion       0.89      0.69      0.78      1978

           accuracy                           0.57     11923
          macro avg       0.63      0.57      0.55     11923
       weighted avg       0.63      0.57      0.55     11923


====================================================================================================
Classification report for: MoritzLaurer/deberta-v3-large-zeroshot-v2.0
                     precision    recall  f1-score   support

                age       0.77      0.44      0.56      1952
          ethnicity       0.80      0.83      0.81      1995
             gender       0.47      0.52      0.49      1952
  not_cyberbullying       0.36      0.75      0.48      2040
other_cyberbullying       0.31      0.12      0.17      2006
           religion       0.87      0.67      0.76      1978

           accuracy                           0.55     11923
          macro avg       0.60      0.55      0.55     11923
       weighted avg       0.59      0.55      0.54     11923

### **OpenAI**

In [31]:
import os
import json
import re
import time
from pathlib import Path

import numpy as np
import pandas as pd
import joblib
from openai import OpenAI

# ----------------------------
# OpenAI configuration
# ----------------------------
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-4.1-mini")
MAX_OPENAI_CASES = None  # set integer (e.g., 200 or 1000) for a smaller quick run
OPENAI_REQUEST_TIMEOUT_SECONDS = 60
OPENAI_MAX_RETRIES = 3

# Checkpoint/resume configuration (same style as Ollama)
OPENAI_CHECKPOINT_EVERY = 25
OPENAI_RESUME_FROM_CHECKPOINT = True
OPENAI_RESET_CHECKPOINT = False

# ----------------------------
# Load .env if present (without requiring python-dotenv)
# ----------------------------
def _load_env_file(env_path: str = ".env") -> None:
    if not os.path.exists(env_path):
        return
    try:
        with open(env_path, "r", encoding="utf-8") as f:
            for raw_line in f:
                line = raw_line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                key, value = line.split("=", 1)
                key = key.strip()
                value = value.strip().strip('"').strip("'")
                if key and key not in os.environ:
                    os.environ[key] = value
    except Exception as e:
        print(f"Warning: Failed to read .env file: {e}")

_load_env_file()
api_key = os.getenv("OPENAI_API_KEY")
if not api_key:
    raise ValueError(
        "OPENAI_API_KEY is not set. Put it in .env as OPENAI_API_KEY=... or export it in your environment."
    )

client = OpenAI(api_key=api_key, timeout=OPENAI_REQUEST_TIMEOUT_SECONDS)

# Reuse same eval split as Ollama section when available.
if "x_test" not in globals():
    x_test = joblib.load(r".\Artifacts\x_test.pkl")
if "y_test" not in globals():
    y_test = joblib.load(r".\Artifacts\y_test.pkl")
if "class_names" not in globals():
    class_names = joblib.load(r".\Artifacts\class_names.pkl")

class_names_list = list(class_names)
label_to_id = {label: i for i, label in enumerate(class_names_list)}
FALLBACK_LABEL = "other_cyberbullying"

if MAX_OPENAI_CASES is None:
    x_eval_openai = list(x_test)
    y_eval_openai = np.asarray(y_test)
else:
    x_eval_openai = list(x_test)[:MAX_OPENAI_CASES]
    y_eval_openai = np.asarray(y_test)[:MAX_OPENAI_CASES]

artifacts_dir = Path(r".\Artifacts")
artifacts_dir.mkdir(parents=True, exist_ok=True)
safe_openai_model = re.sub(r"[^a-zA-Z0-9_.-]", "_", OPENAI_MODEL)
openai_checkpoint_path = artifacts_dir / f"openai_checkpoint_{safe_openai_model}.pkl"
openai_predictions_path = artifacts_dir / f"openai_predictions_{safe_openai_model}.pkl"

if OPENAI_RESET_CHECKPOINT and openai_checkpoint_path.exists():
    openai_checkpoint_path.unlink()
    print(f"Deleted old OpenAI checkpoint: {openai_checkpoint_path}")

SYSTEM_PROMPT = f"""You are an expert annotator for cyberbullying tweet classification.

Valid labels: {class_names_list}

Rules:
1) Return exactly one label from the valid label list.
2) Output STRICT JSON only, with this schema:
   {{"label": "<one_valid_label>"}}
3) Do not output markdown, code fences, or any extra keys.
"""

def _parse_json_payload(raw_text: str):
    text = (raw_text or "").strip()
    try:
        return json.loads(text)
    except Exception:
        pass
    text = re.sub(r"^```(?:json)?\s*|\s*```$", "", text, flags=re.IGNORECASE | re.DOTALL).strip()
    return json.loads(text)

def _normalize_text(s: str) -> str:
    return re.sub(r"[^a-z0-9_]+", "", (s or "").strip().lower())

normalized_label_to_canonical = {_normalize_text(label): label for label in class_names_list}

def _map_to_valid_label(raw_label: str) -> str:
    if raw_label in label_to_id:
        return raw_label

    raw_norm = _normalize_text(raw_label)
    if raw_norm in normalized_label_to_canonical:
        return normalized_label_to_canonical[raw_norm]

    for cls in class_names_list:
        cls_norm = _normalize_text(cls)
        if cls_norm and cls_norm in raw_norm:
            return cls

    if FALLBACK_LABEL in label_to_id:
        return FALLBACK_LABEL

    raise ValueError(
        f"Invalid label returned and fallback label not found: {raw_label}. "
        f"Expected one of {class_names_list} with fallback '{FALLBACK_LABEL}'."
    )

def openai_predict_one(tweet_text: str):
    last_error = None
    user_prompt = f"Classify this tweet:\n\n{tweet_text}"

    for attempt in range(1, OPENAI_MAX_RETRIES + 1):
        try:
            resp = client.chat.completions.create(
                model=OPENAI_MODEL,
                temperature=0,
                response_format={"type": "json_object"},
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": user_prompt},
                ],
            )
            content = resp.choices[0].message.content
            payload = _parse_json_payload(content)
            raw_label = str(payload.get("label", "")).strip()
            final_label = _map_to_valid_label(raw_label)
            return label_to_id[final_label], final_label
        except Exception as err:
            last_error = err
            if attempt < OPENAI_MAX_RETRIES:
                time.sleep(1.2 * attempt)

    raise RuntimeError(f"OpenAI prediction failed after retries: {last_error}")

def save_openai_checkpoint(next_index: int, pred_ids, pred_rows):
    state = {
        "model": OPENAI_MODEL,
        "x_eval_size": len(x_eval_openai),
        "next_index": int(next_index),
        "pred_ids": list(pred_ids),
        "pred_rows": list(pred_rows),
        "saved_at_unix": time.time(),
    }
    joblib.dump(state, openai_checkpoint_path)

# ----------------------------
# Resume from checkpoint if available
# ----------------------------
openai_pred_ids = []
openai_rows = []
openai_start_index = 0

if OPENAI_RESUME_FROM_CHECKPOINT and openai_checkpoint_path.exists():
    state = joblib.load(openai_checkpoint_path)
    same_model = state.get("model") == OPENAI_MODEL
    same_size = int(state.get("x_eval_size", -1)) == len(x_eval_openai)
    if same_model and same_size:
        openai_pred_ids = list(state.get("pred_ids", []))
        openai_rows = list(state.get("pred_rows", []))
        openai_start_index = int(state.get("next_index", len(openai_pred_ids)))
        openai_start_index = max(0, min(openai_start_index, len(x_eval_openai)))
        print(f"Resumed OpenAI checkpoint: {openai_checkpoint_path}")
        print(f"Loaded {len(openai_pred_ids)} saved predictions; continuing from index {openai_start_index}")
    else:
        print("OpenAI checkpoint found but skipped due to model/test-size mismatch.")

# ----------------------------
# Run OpenAI prediction for each tweet
# ----------------------------
openai_total = len(x_eval_openai)
openai_start_time = time.time()

for idx in range(openai_start_index, openai_total):
    tweet_text = x_eval_openai[idx]
    pred_id, pred_label = openai_predict_one(str(tweet_text))
    openai_pred_ids.append(int(pred_id))
    openai_rows.append({
        "tweet": str(tweet_text),
        "y_test_label": class_names_list[int(y_eval_openai[idx])],
        "openai_prediction": pred_label,
    })

    processed = idx + 1
    if (processed % OPENAI_CHECKPOINT_EVERY == 0) or (processed == openai_total):
        save_openai_checkpoint(next_index=processed, pred_ids=openai_pred_ids, pred_rows=openai_rows)
        elapsed = time.time() - openai_start_time
        done_now = max(1, processed - openai_start_index)
        sec_per_tweet = elapsed / done_now
        remaining = openai_total - processed
        eta_min = (remaining * sec_per_tweet) / 60.0
        print(f"OpenAI progress: {processed}/{openai_total} | checkpoint saved | ETA ~ {eta_min:.1f} min")

# Convert and save final artifacts
openai_pred_ids = np.asarray(openai_pred_ids, dtype=int)
openai_pred_df = pd.DataFrame(openai_rows)
openai_pred_df["is_match"] = openai_pred_df["y_test_label"] == openai_pred_df["openai_prediction"]

openai_prediction_compare_df = openai_pred_df[[
    "tweet",
    "y_test_label",
    "openai_prediction",
    "is_match",
]].copy()

joblib.dump(
    {
        "openai_pred_ids": openai_pred_ids,
        "prediction_compare_df": openai_prediction_compare_df,
        "model": OPENAI_MODEL,
        "x_eval_size": len(x_eval_openai),
    },
    openai_predictions_path,
 )

display(openai_prediction_compare_df.head(20))
print(f"Done. Collected {len(openai_pred_ids)} predictions from model: {OPENAI_MODEL}")
print(f"Total exact label matches: {int(openai_prediction_compare_df['is_match'].sum())}/{len(openai_prediction_compare_df)}")
print(f"OpenAI checkpoint file: {openai_checkpoint_path}")
print(f"OpenAI predictions artifact: {openai_predictions_path}")

OpenAI progress: 25/11923 | checkpoint saved | ETA ~ 175.0 min
OpenAI progress: 50/11923 | checkpoint saved | ETA ~ 158.4 min
OpenAI progress: 75/11923 | checkpoint saved | ETA ~ 155.9 min
OpenAI progress: 100/11923 | checkpoint saved | ETA ~ 152.8 min
OpenAI progress: 125/11923 | checkpoint saved | ETA ~ 146.7 min
OpenAI progress: 150/11923 | checkpoint saved | ETA ~ 148.2 min
OpenAI progress: 175/11923 | checkpoint saved | ETA ~ 151.1 min
OpenAI progress: 200/11923 | checkpoint saved | ETA ~ 152.5 min
OpenAI progress: 225/11923 | checkpoint saved | ETA ~ 157.9 min
OpenAI progress: 250/11923 | checkpoint saved | ETA ~ 158.9 min
OpenAI progress: 275/11923 | checkpoint saved | ETA ~ 156.9 min
OpenAI progress: 300/11923 | checkpoint saved | ETA ~ 157.2 min
OpenAI progress: 325/11923 | checkpoint saved | ETA ~ 154.9 min
OpenAI progress: 350/11923 | checkpoint saved | ETA ~ 153.5 min
OpenAI progress: 375/11923 | checkpoint saved | ETA ~ 150.3 min
OpenAI progress: 400/11923 | checkpoint saved | ETA ~ 149.1 min
OpenAI progress: 425/11923 | checkpoint saved | ETA ~ 147.7 min
OpenAI progress: 450/11923 | checkpoint saved | ETA ~ 147.6 min
OpenAI progress: 475/11923 | checkpoint saved | ETA ~ 149.7 min
OpenAI progress: 500/11923 | checkpoint saved | ETA ~ 150.5 min
OpenAI progress: 525/11923 | checkpoint saved | ETA ~ 150.6 min
OpenAI progress: 550/11923 | checkpoint saved | ETA ~ 149.4 min
OpenAI progress: 575/11923 | checkpoint saved | ETA ~ 148.9 min
OpenAI progress: 600/11923 | checkpoint saved | ETA ~ 148.3 min
OpenAI progress: 625/11923 | checkpoint saved | ETA ~ 148.4 min
OpenAI progress: 650/11923 | checkpoint saved | ETA ~ 148.4 min
OpenAI progress: 675/11923 | checkpoint saved | ETA ~ 150.9 min
OpenAI progress: 700/11923 | checkpoint saved | ETA ~ 149.9 min
OpenAI progress: 725/11923 | checkpoint saved | ETA ~ 149.4 min
OpenAI progress: 750/11923 | checkpoint saved | ETA ~ 148.1 min
OpenAI progress: 775/11923 | checkpoint saved | ETA ~ 147.0 min
OpenAI progress: 800/11923 | checkpoint saved | ETA ~ 145.9 min
OpenAI progress: 825/11923 | checkpoint saved | ETA ~ 144.7 min
OpenAI progress: 850/11923 | checkpoint saved | ETA ~ 143.4 min
OpenAI progress: 875/11923 | checkpoint saved | ETA ~ 142.1 min
OpenAI progress: 900/11923 | checkpoint saved | ETA ~ 142.1 min
OpenAI progress: 925/11923 | checkpoint saved | ETA ~ 141.0 min
OpenAI progress: 950/11923 | checkpoint saved | ETA ~ 140.4 min
OpenAI progress: 975/11923 | checkpoint saved | ETA ~ 139.7 min
OpenAI progress: 1000/11923 | checkpoint saved | ETA ~ 139.1 min
OpenAI progress: 1025/11923 | checkpoint saved | ETA ~ 138.0 min
OpenAI progress: 1050/11923 | checkpoint saved | ETA ~ 138.0 min
OpenAI progress: 1075/11923 | checkpoint saved | ETA ~ 137.1 min
OpenAI progress: 1100/11923 | checkpoint saved | ETA ~ 136.3 min
OpenAI progress: 1125/11923 | checkpoint saved | ETA ~ 135.2 min
OpenAI progress: 1150/11923 | checkpoint saved | ETA ~ 134.0 min
OpenAI progress: 1175/11923 | checkpoint saved | ETA ~ 133.7 min
OpenAI progress: 1200/11923 | checkpoint saved | ETA ~ 132.9 min
OpenAI progress: 1225/11923 | checkpoint saved | ETA ~ 131.9 min
OpenAI progress: 1250/11923 | checkpoint saved | ETA ~ 131.9 min
OpenAI progress: 1275/11923 | checkpoint saved | ETA ~ 130.8 min
OpenAI progress: 1300/11923 | checkpoint saved | ETA ~ 130.2 min
OpenAI progress: 1325/11923 | checkpoint saved | ETA ~ 129.4 min
OpenAI progress: 1350/11923 | checkpoint saved | ETA ~ 128.7 min
OpenAI progress: 1375/11923 | checkpoint saved | ETA ~ 127.9 min
OpenAI progress: 1400/11923 | checkpoint saved | ETA ~ 127.8 min
OpenAI progress: 1425/11923 | checkpoint saved | ETA ~ 126.9 min
OpenAI progress: 1450/11923 | checkpoint saved | ETA ~ 126.9 min
OpenAI progress: 1475/11923 | checkpoint saved | ETA ~ 126.3 min
OpenAI progress: 1500/11923 | checkpoint saved | ETA ~ 126.4 min
OpenAI progress: 1525/11923 | checkpoint saved | ETA ~ 125.5 min
OpenAI progress: 1550/11923 | checkpoint saved | ETA ~ 124.8 min
OpenAI progress: 1575/11923 | checkpoint saved | ETA ~ 124.0 min
OpenAI progress: 1600/11923 | checkpoint saved | ETA ~ 123.5 min
OpenAI progress: 1625/11923 | checkpoint saved | ETA ~ 122.7 min
OpenAI progress: 1650/11923 | checkpoint saved | ETA ~ 121.9 min
OpenAI progress: 1675/11923 | checkpoint saved | ETA ~ 121.2 min
OpenAI progress: 1700/11923 | checkpoint saved | ETA ~ 120.6 min
OpenAI progress: 1725/11923 | checkpoint saved | ETA ~ 120.2 min
OpenAI progress: 1750/11923 | checkpoint saved | ETA ~ 119.6 min
OpenAI progress: 1775/11923 | checkpoint saved | ETA ~ 119.1 min
OpenAI progress: 1800/11923 | checkpoint saved | ETA ~ 118.5 min
OpenAI progress: 1825/11923 | checkpoint saved | ETA ~ 118.0 min
OpenAI progress: 1850/11923 | checkpoint saved | ETA ~ 117.2 min
OpenAI progress: 1875/11923 | checkpoint saved | ETA ~ 116.6 min
OpenAI progress: 1900/11923 | checkpoint saved | ETA ~ 115.8 min
OpenAI progress: 1925/11923 | checkpoint saved | ETA ~ 115.4 min
OpenAI progress: 1950/11923 | checkpoint saved | ETA ~ 114.8 min
OpenAI progress: 1975/11923 | checkpoint saved | ETA ~ 114.2 min
OpenAI progress: 2000/11923 | checkpoint saved | ETA ~ 113.8 min
OpenAI progress: 2025/11923 | checkpoint saved | ETA ~ 113.3 min
OpenAI progress: 2050/11923 | checkpoint saved | ETA ~ 112.9 min
OpenAI progress: 2075/11923 | checkpoint saved | ETA ~ 112.7 min
OpenAI progress: 2100/11923 | checkpoint saved | ETA ~ 112.2 min
OpenAI progress: 2125/11923 | checkpoint saved | ETA ~ 111.9 min
OpenAI progress: 2150/11923 | checkpoint saved | ETA ~ 111.5 min
OpenAI progress: 2175/11923 | checkpoint saved | ETA ~ 111.0 min
OpenAI progress: 2200/11923 | checkpoint saved | ETA ~ 110.5 min
OpenAI progress: 2225/11923 | checkpoint saved | ETA ~ 110.1 min
OpenAI progress: 2250/11923 | checkpoint saved | ETA ~ 109.6 min
OpenAI progress: 2275/11923 | checkpoint saved | ETA ~ 109.0 min
OpenAI progress: 2300/11923 | checkpoint saved | ETA ~ 109.0 min
OpenAI progress: 2325/11923 | checkpoint saved | ETA ~ 108.8 min
OpenAI progress: 2350/11923 | checkpoint saved | ETA ~ 108.2 min
OpenAI progress: 2375/11923 | checkpoint saved | ETA ~ 107.6 min
OpenAI progress: 2400/11923 | checkpoint saved | ETA ~ 107.2 min
OpenAI progress: 2425/11923 | checkpoint saved | ETA ~ 106.7 min
OpenAI progress: 2450/11923 | checkpoint saved | ETA ~ 106.1 min
OpenAI progress: 2475/11923 | checkpoint saved | ETA ~ 105.7 min
OpenAI progress: 2500/11923 | checkpoint saved | ETA ~ 105.2 min
OpenAI progress: 2525/11923 | checkpoint saved | ETA ~ 104.7 min
OpenAI progress: 2550/11923 | checkpoint saved | ETA ~ 104.3 min
OpenAI progress: 2575/11923 | checkpoint saved | ETA ~ 103.8 min
OpenAI progress: 2600/11923 | checkpoint saved | ETA ~ 103.4 min
OpenAI progress: 2625/11923 | checkpoint saved | ETA ~ 103.0 min
OpenAI progress: 2650/11923 | checkpoint saved | ETA ~ 102.5 min
OpenAI progress: 2675/11923 | checkpoint saved | ETA ~ 102.1 min
OpenAI progress: 2700/11923 | checkpoint saved | ETA ~ 101.8 min
OpenAI progress: 2725/11923 | checkpoint saved | ETA ~ 101.4 min
OpenAI progress: 2750/11923 | checkpoint saved | ETA ~ 101.0 min
OpenAI progress: 2775/11923 | checkpoint saved | ETA ~ 100.7 min
OpenAI progress: 2800/11923 | checkpoint saved | ETA ~ 100.3 min
OpenAI progress: 2825/11923 | checkpoint saved | ETA ~ 100.2 min
OpenAI progress: 2850/11923 | checkpoint saved | ETA ~ 99.8 min
OpenAI progress: 2875/11923 | checkpoint saved | ETA ~ 99.3 min
OpenAI progress: 2900/11923 | checkpoint saved | ETA ~ 98.9 min
OpenAI progress: 2925/11923 | checkpoint saved | ETA ~ 98.4 min
OpenAI progress: 2950/11923 | checkpoint saved | ETA ~ 98.0 min
OpenAI progress: 2975/11923 | checkpoint saved | ETA ~ 97.6 min
OpenAI progress: 3000/11923 | checkpoint saved | ETA ~ 97.3 min
OpenAI progress: 3025/11923 | checkpoint saved | ETA ~ 96.9 min
OpenAI progress: 3050/11923 | checkpoint saved | ETA ~ 96.8 min
OpenAI progress: 3075/11923 | checkpoint saved | ETA ~ 96.4 min
OpenAI progress: 3100/11923 | checkpoint saved | ETA ~ 96.0 min
OpenAI progress: 3125/11923 | checkpoint saved | ETA ~ 95.7 min
OpenAI progress: 3150/11923 | checkpoint saved | ETA ~ 95.4 min
OpenAI progress: 3175/11923 | checkpoint saved | ETA ~ 95.1 min
OpenAI progress: 3200/11923 | checkpoint saved | ETA ~ 94.8 min
OpenAI progress: 3225/11923 | checkpoint saved | ETA ~ 94.5 min
OpenAI progress: 3250/11923 | checkpoint saved | ETA ~ 94.3 min
OpenAI progress: 3275/11923 | checkpoint saved | ETA ~ 94.0 min
OpenAI progress: 3300/11923 | checkpoint saved | ETA ~ 93.6 min
OpenAI progress: 3325/11923 | checkpoint saved | ETA ~ 93.2 min
OpenAI progress: 3350/11923 | checkpoint saved | ETA ~ 93.0 min
OpenAI progress: 3375/11923 | checkpoint saved | ETA ~ 92.7 min
OpenAI progress: 3400/11923 | checkpoint saved | ETA ~ 92.3 min
OpenAI progress: 3425/11923 | checkpoint saved | ETA ~ 92.1 min
OpenAI progress: 3450/11923 | checkpoint saved | ETA ~ 91.8 min
OpenAI progress: 3475/11923 | checkpoint saved | ETA ~ 91.5 min
OpenAI progress: 3500/11923 | checkpoint saved | ETA ~ 91.2 min
OpenAI progress: 3525/11923 | checkpoint saved | ETA ~ 90.8 min
OpenAI progress: 3550/11923 | checkpoint saved | ETA ~ 90.6 min
OpenAI progress: 3575/11923 | checkpoint saved | ETA ~ 90.3 min
OpenAI progress: 3600/11923 | checkpoint saved | ETA ~ 90.0 min
OpenAI progress: 3625/11923 | checkpoint saved | ETA ~ 89.7 min
OpenAI progress: 3650/11923 | checkpoint saved | ETA ~ 89.3 min
OpenAI progress: 3675/11923 | checkpoint saved | ETA ~ 89.0 min
OpenAI progress: 3700/11923 | checkpoint saved | ETA ~ 88.7 min
OpenAI progress: 3725/11923 | checkpoint saved | ETA ~ 88.3 min
OpenAI progress: 3750/11923 | checkpoint saved | ETA ~ 88.0 min
OpenAI progress: 3775/11923 | checkpoint saved | ETA ~ 87.7 min
OpenAI progress: 3800/11923 | checkpoint saved | ETA ~ 87.3 min
OpenAI progress: 3825/11923 | checkpoint saved | ETA ~ 87.0 min
OpenAI progress: 3850/11923 | checkpoint saved | ETA ~ 86.6 min
OpenAI progress: 3875/11923 | checkpoint saved | ETA ~ 86.3 min
OpenAI progress: 3900/11923 | checkpoint saved | ETA ~ 85.9 min
OpenAI progress: 3925/11923 | checkpoint saved | ETA ~ 85.5 min
OpenAI progress: 3950/11923 | checkpoint saved | ETA ~ 85.2 min
OpenAI progress: 3975/11923 | checkpoint saved | ETA ~ 84.8 min
OpenAI progress: 4000/11923 | checkpoint saved | ETA ~ 84.5 min
OpenAI progress: 4025/11923 | checkpoint saved | ETA ~ 84.2 min
OpenAI progress: 4050/11923 | checkpoint saved | ETA ~ 84.0 min
OpenAI progress: 4075/11923 | checkpoint saved | ETA ~ 83.6 min
OpenAI progress: 4100/11923 | checkpoint saved | ETA ~ 83.3 min
OpenAI progress: 4125/11923 | checkpoint saved | ETA ~ 83.0 min
OpenAI progress: 4150/11923 | checkpoint saved | ETA ~ 82.8 min
OpenAI progress: 4175/11923 | checkpoint saved | ETA ~ 82.5 min
OpenAI progress: 4200/11923 | checkpoint saved | ETA ~ 82.3 min
OpenAI progress: 4225/11923 | checkpoint saved | ETA ~ 82.0 min
OpenAI progress: 4250/11923 | checkpoint saved | ETA ~ 81.7 min
OpenAI progress: 4275/11923 | checkpoint saved | ETA ~ 81.4 min
OpenAI progress: 4300/11923 | checkpoint saved | ETA ~ 81.2 min
OpenAI progress: 4325/11923 | checkpoint saved | ETA ~ 81.4 min
OpenAI progress: 4350/11923 | checkpoint saved | ETA ~ 81.0 min
OpenAI progress: 4375/11923 | checkpoint saved | ETA ~ 80.7 min
OpenAI progress: 4400/11923 | checkpoint saved | ETA ~ 80.4 min
OpenAI progress: 4425/11923 | checkpoint saved | ETA ~ 80.0 min
OpenAI progress: 4450/11923 | checkpoint saved | ETA ~ 79.7 min
OpenAI progress: 4475/11923 | checkpoint saved | ETA ~ 79.4 min
OpenAI progress: 4500/11923 | checkpoint saved | ETA ~ 79.2 min
OpenAI progress: 4525/11923 | checkpoint saved | ETA ~ 78.9 min
OpenAI progress: 4550/11923 | checkpoint saved | ETA ~ 78.5 min
OpenAI progress: 4575/11923 | checkpoint saved | ETA ~ 78.2 min
OpenAI progress: 4600/11923 | checkpoint saved | ETA ~ 77.9 min
OpenAI progress: 4625/11923 | checkpoint saved | ETA ~ 77.7 min
OpenAI progress: 4650/11923 | checkpoint saved | ETA ~ 77.4 min
OpenAI progress: 4675/11923 | checkpoint saved | ETA ~ 77.1 min
OpenAI progress: 4700/11923 | checkpoint saved | ETA ~ 76.8 min
OpenAI progress: 4725/11923 | checkpoint saved | ETA ~ 76.5 min
OpenAI progress: 4750/11923 | checkpoint saved | ETA ~ 76.2 min
OpenAI progress: 4775/11923 | checkpoint saved | ETA ~ 75.9 min
OpenAI progress: 4800/11923 | checkpoint saved | ETA ~ 75.6 min
OpenAI progress: 4825/11923 | checkpoint saved | ETA ~ 75.3 min
OpenAI progress: 4850/11923 | checkpoint saved | ETA ~ 75.0 min
OpenAI progress: 4875/11923 | checkpoint saved | ETA ~ 74.8 min
OpenAI progress: 4900/11923 | checkpoint saved | ETA ~ 74.5 min
OpenAI progress: 4925/11923 | checkpoint saved | ETA ~ 74.4 min
OpenAI progress: 4950/11923 | checkpoint saved | ETA ~ 74.0 min
OpenAI progress: 4975/11923 | checkpoint saved | ETA ~ 73.7 min
OpenAI progress: 5000/11923 | checkpoint saved | ETA ~ 73.4 min
OpenAI progress: 5025/11923 | checkpoint saved | ETA ~ 73.2 min
OpenAI progress: 5050/11923 | checkpoint saved | ETA ~ 72.8 min
OpenAI progress: 5075/11923 | checkpoint saved | ETA ~ 72.5 min
OpenAI progress: 5100/11923 | checkpoint saved | ETA ~ 72.2 min
OpenAI progress: 5125/11923 | checkpoint saved | ETA ~ 71.8 min
OpenAI progress: 5150/11923 | checkpoint saved | ETA ~ 71.5 min
OpenAI progress: 5175/11923 | checkpoint saved | ETA ~ 71.2 min
OpenAI progress: 5200/11923 | checkpoint saved | ETA ~ 70.9 min
OpenAI progress: 5225/11923 | checkpoint saved | ETA ~ 70.6 min
OpenAI progress: 5250/11923 | checkpoint saved | ETA ~ 70.4 min
OpenAI progress: 5275/11923 | checkpoint saved | ETA ~ 70.1 min
OpenAI progress: 5300/11923 | checkpoint saved | ETA ~ 69.8 min
OpenAI progress: 5325/11923 | checkpoint saved | ETA ~ 69.5 min
OpenAI progress: 5350/11923 | checkpoint saved | ETA ~ 69.2 min
OpenAI progress: 5375/11923 | checkpoint saved | ETA ~ 68.9 min
OpenAI progress: 5400/11923 | checkpoint saved | ETA ~ 68.6 min
OpenAI progress: 5425/11923 | checkpoint saved | ETA ~ 68.3 min
OpenAI progress: 5450/11923 | checkpoint saved | ETA ~ 68.0 min
OpenAI progress: 5475/11923 | checkpoint saved | ETA ~ 67.7 min
OpenAI progress: 5500/11923 | checkpoint saved | ETA ~ 67.4 min
OpenAI progress: 5525/11923 | checkpoint saved | ETA ~ 67.1 min
OpenAI progress: 5550/11923 | checkpoint saved | ETA ~ 66.9 min
OpenAI progress: 5575/11923 | checkpoint saved | ETA ~ 66.6 min
OpenAI progress: 5600/11923 | checkpoint saved | ETA ~ 66.4 min
OpenAI progress: 5625/11923 | checkpoint saved | ETA ~ 66.1 min
OpenAI progress: 5650/11923 | checkpoint saved | ETA ~ 65.8 min
OpenAI progress: 5675/11923 | checkpoint saved | ETA ~ 65.5 min
OpenAI progress: 5700/11923 | checkpoint saved | ETA ~ 65.2 min
OpenAI progress: 5725/11923 | checkpoint saved | ETA ~ 64.9 min
OpenAI progress: 5750/11923 | checkpoint saved | ETA ~ 64.6 min
OpenAI progress: 5775/11923 | checkpoint saved | ETA ~ 64.3 min
OpenAI progress: 5800/11923 | checkpoint saved | ETA ~ 64.0 min
OpenAI progress: 5825/11923 | checkpoint saved | ETA ~ 63.7 min
OpenAI progress: 5850/11923 | checkpoint saved | ETA ~ 63.4 min
OpenAI progress: 5875/11923 | checkpoint saved | ETA ~ 63.1 min
OpenAI progress: 5900/11923 | checkpoint saved | ETA ~ 62.8 min
OpenAI progress: 5925/11923 | checkpoint saved | ETA ~ 62.6 min
OpenAI progress: 5950/11923 | checkpoint saved | ETA ~ 62.3 min
OpenAI progress: 5975/11923 | checkpoint saved | ETA ~ 62.0 min
OpenAI progress: 6000/11923 | checkpoint saved | ETA ~ 61.7 min
OpenAI progress: 6025/11923 | checkpoint saved | ETA ~ 61.5 min
OpenAI progress: 6050/11923 | checkpoint saved | ETA ~ 61.2 min
OpenAI progress: 6075/11923 | checkpoint saved | ETA ~ 61.0 min
OpenAI progress: 6100/11923 | checkpoint saved | ETA ~ 60.7 min
OpenAI progress: 6125/11923 | checkpoint saved | ETA ~ 60.5 min
OpenAI progress: 6150/11923 | checkpoint saved | ETA ~ 60.2 min
OpenAI progress: 6175/11923 | checkpoint saved | ETA ~ 59.9 min
OpenAI progress: 6200/11923 | checkpoint saved | ETA ~ 59.7 min
OpenAI progress: 6225/11923 | checkpoint saved | ETA ~ 59.4 min
OpenAI progress: 6250/11923 | checkpoint saved | ETA ~ 59.2 min
OpenAI progress: 6275/11923 | checkpoint saved | ETA ~ 58.9 min
OpenAI progress: 6300/11923 | checkpoint saved | ETA ~ 58.7 min
OpenAI progress: 6325/11923 | checkpoint saved | ETA ~ 58.5 min
OpenAI progress: 6350/11923 | checkpoint saved | ETA ~ 58.2 min
OpenAI progress: 6375/11923 | checkpoint saved | ETA ~ 58.0 min
OpenAI progress: 6400/11923 | checkpoint saved | ETA ~ 57.7 min
OpenAI progress: 6425/11923 | checkpoint saved | ETA ~ 57.4 min
OpenAI progress: 6450/11923 | checkpoint saved | ETA ~ 57.1 min
OpenAI progress: 6475/11923 | checkpoint saved | ETA ~ 56.8 min
OpenAI progress: 6500/11923 | checkpoint saved | ETA ~ 56.5 min
OpenAI progress: 6525/11923 | checkpoint saved | ETA ~ 56.3 min
OpenAI progress: 6550/11923 | checkpoint saved | ETA ~ 56.0 min
OpenAI progress: 6575/11923 | checkpoint saved | ETA ~ 55.7 min
OpenAI progress: 6600/11923 | checkpoint saved | ETA ~ 55.4 min
OpenAI progress: 6625/11923 | checkpoint saved | ETA ~ 55.2 min
OpenAI progress: 6650/11923 | checkpoint saved | ETA ~ 54.9 min
OpenAI progress: 6675/11923 | checkpoint saved | ETA ~ 54.6 min
OpenAI progress: 6700/11923 | checkpoint saved | ETA ~ 54.3 min
OpenAI progress: 6725/11923 | checkpoint saved | ETA ~ 54.0 min
OpenAI progress: 6750/11923 | checkpoint saved | ETA ~ 53.7 min
OpenAI progress: 6775/11923 | checkpoint saved | ETA ~ 53.4 min
OpenAI progress: 6800/11923 | checkpoint saved | ETA ~ 53.2 min
OpenAI progress: 6825/11923 | checkpoint saved | ETA ~ 52.9 min
OpenAI progress: 6850/11923 | checkpoint saved | ETA ~ 52.6 min
OpenAI progress: 6875/11923 | checkpoint saved | ETA ~ 52.3 min
OpenAI progress: 6900/11923 | checkpoint saved | ETA ~ 52.1 min
OpenAI progress: 6925/11923 | checkpoint saved | ETA ~ 51.8 min
OpenAI progress: 6950/11923 | checkpoint saved | ETA ~ 51.5 min
OpenAI progress: 6975/11923 | checkpoint saved | ETA ~ 51.2 min
OpenAI progress: 7000/11923 | checkpoint saved | ETA ~ 51.0 min
OpenAI progress: 7025/11923 | checkpoint saved | ETA ~ 50.7 min
OpenAI progress: 7050/11923 | checkpoint saved | ETA ~ 50.5 min
OpenAI progress: 7075/11923 | checkpoint saved | ETA ~ 50.2 min
OpenAI progress: 7100/11923 | checkpoint saved | ETA ~ 49.9 min
OpenAI progress: 7125/11923 | checkpoint saved | ETA ~ 49.7 min
OpenAI progress: 7150/11923 | checkpoint saved | ETA ~ 49.4 min
OpenAI progress: 7175/11923 | checkpoint saved | ETA ~ 49.1 min
OpenAI progress: 7200/11923 | checkpoint saved | ETA ~ 48.8 min
OpenAI progress: 7225/11923 | checkpoint saved | ETA ~ 48.6 min
OpenAI progress: 7250/11923 | checkpoint saved | ETA ~ 48.3 min
OpenAI progress: 7275/11923 | checkpoint saved | ETA ~ 48.7 min
OpenAI progress: 7300/11923 | checkpoint saved | ETA ~ 48.3 min
OpenAI progress: 7325/11923 | checkpoint saved | ETA ~ 48.1 min
OpenAI progress: 7350/11923 | checkpoint saved | ETA ~ 47.8 min
OpenAI progress: 7375/11923 | checkpoint saved | ETA ~ 47.5 min
OpenAI progress: 7400/11923 | checkpoint saved | ETA ~ 47.2 min
OpenAI progress: 7425/11923 | checkpoint saved | ETA ~ 47.0 min
OpenAI progress: 7450/11923 | checkpoint saved | ETA ~ 46.7 min
OpenAI progress: 7475/11923 | checkpoint saved | ETA ~ 46.4 min
OpenAI progress: 7500/11923 | checkpoint saved | ETA ~ 46.1 min
OpenAI progress: 7525/11923 | checkpoint saved | ETA ~ 45.8 min
OpenAI progress: 7550/11923 | checkpoint saved | ETA ~ 45.5 min
OpenAI progress: 7575/11923 | checkpoint saved | ETA ~ 45.3 min
OpenAI progress: 7600/11923 | checkpoint saved | ETA ~ 45.0 min
OpenAI progress: 7625/11923 | checkpoint saved | ETA ~ 44.8 min
OpenAI progress: 7650/11923 | checkpoint saved | ETA ~ 44.5 min
OpenAI progress: 7675/11923 | checkpoint saved | ETA ~ 44.2 min
OpenAI progress: 7700/11923 | checkpoint saved | ETA ~ 43.9 min
OpenAI progress: 7725/11923 | checkpoint saved | ETA ~ 43.7 min
OpenAI progress: 7750/11923 | checkpoint saved | ETA ~ 43.4 min
OpenAI progress: 7775/11923 | checkpoint saved | ETA ~ 43.1 min

,tweet,y_test_label,openai_prediction,is_match
0,today tomorrow try move mountains cross fingers,other_cyberbullying,not_cyberbullying,False
1,typa girl bullied lesbians high school,age,gender,False
2,cool woman gave directions polling place whose...,age,gender,False
3,need teach version quran terrorists killing pe...,religion,religion,True
4,rome destroy coliseum roman forum every buildi...,religion,religion,True
5,try hide jihadi propaganda know hell gys specl...,religion,religion,True
6,city college,not_cyberbullying,not_cyberbullying,True
7,pepperidge farm remembers,other_cyberbullying,not_cyberbullying,False
8,added feminazi white knight professional victi...,other_cyberbullying,gender,False
9,blm something know muslim leaders record stati...,religion,religion,True
10,life better sex know sex know someone dying se...,not_cyberbullying,not_cyberbullying,True
11,bullied high school girl fat karma really come...,age,other_cyberbullying,False
12,always ignore people get mixed always call “se...,gender,gender,True
13,lot people cell phones one years used idea dis...,other_cyberbullying,not_cyberbullying,False
14,yours mine enforced men jail visitation these ...,gender,not_cyberbullying,False
15,fucking love her hot shit,not_cyberbullying,not_cyberbullying,True
16,gay marriage think rape ever joke rape chances...,gender,other_cyberbullying,False
17,uscirf biased blindfolded islamic terrorism ri...,religion,religion,True
18,liked video httptcoqigeerlzpj rape fraud femin...,gender,other_cyberbullying,False
19,ummm what even muslim nation y’all act like ai...,religion,religion,True

Done. Collected 11923 predictions from model: gpt-4.1-mini
Total exact label matches: 6215/11923
OpenAI checkpoint file: Artifacts\openai_checkpoint_gpt-4.1-mini.pkl
OpenAI predictions artifact: Artifacts\openai_predictions_gpt-4.1-mini.pkl

#### **Evaluation**

In [32]:
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, classification_report

# Ensure y_eval is integer index array and lengths match OpenAI predictions.
y_eval_openai_idx = np.asarray(y_eval_openai).astype(int)
openai_pred_idx = np.asarray(openai_pred_ids).astype(int)

if len(y_eval_openai_idx) != len(openai_pred_idx):
    raise ValueError(
        f"Length mismatch: y_eval_openai has {len(y_eval_openai_idx)} rows, openai_pred has {len(openai_pred_idx)} rows"
    )

# Keep readable labels and index columns for inspection.
openai_pred_df["true_label_idx"] = y_eval_openai_idx
openai_pred_df["openai_pred_idx"] = openai_pred_idx
display(openai_pred_df.head(10))

p, r, f1, support = precision_recall_fscore_support(
    y_eval_openai_idx,
    openai_pred_idx,
    average="weighted",
    zero_division=0,
 )

openai_metrics = {
    "Accuracy": accuracy_score(y_eval_openai_idx, openai_pred_idx),
    "Precision": p,
    "Recall": r,
    "F1-Score": f1,
    "Support": int(len(y_eval_openai_idx)),
}

openai_metrics_df = pd.DataFrame(openai_metrics, index=[OPENAI_MODEL]).T
display(openai_metrics_df)

print("\nOpenAI classification report:\n")
print(
    classification_report(
        y_eval_openai_idx,
        openai_pred_idx,
        target_names=class_names_list,
        zero_division=0,
    )
)

,tweet,y_test_label,openai_prediction,is_match,true_label_idx,openai_pred_idx
0,today tomorrow try move mountains cross fingers,other_cyberbullying,not_cyberbullying,False,4,3
1,typa girl bullied lesbians high school,age,gender,False,0,2
2,cool woman gave directions polling place whose...,age,gender,False,0,2
3,need teach version quran terrorists killing pe...,religion,religion,True,5,5
4,rome destroy coliseum roman forum every buildi...,religion,religion,True,5,5
5,try hide jihadi propaganda know hell gys specl...,religion,religion,True,5,5
6,city college,not_cyberbullying,not_cyberbullying,True,3,3
7,pepperidge farm remembers,other_cyberbullying,not_cyberbullying,False,4,3
8,added feminazi white knight professional victi...,other_cyberbullying,gender,False,4,2
9,blm something know muslim leaders record stati...,religion,religion,True,5,5

           gpt-4.1-mini
Accuracy       0.521261
Precision      0.599045
Recall         0.521261
F1-Score       0.498640
Support    11923.000000

OpenAI classification report:

                     precision    recall  f1-score   support

                age       0.71      0.04      0.08      1952
          ethnicity       0.85      0.87      0.86      1995
             gender       0.58      0.42      0.49      1952
  not_cyberbullying       0.40      0.77      0.53      2040
other_cyberbullying       0.14      0.19      0.16      2006
           religion       0.92      0.82      0.87      1978

           accuracy                           0.52     11923
          macro avg       0.60      0.52      0.50     11923
       weighted avg       0.60      0.52      0.50     11923